### ISSUE TITLE
Static method to generate url from path and data

### ISSUE THREAD

**Issue by mikalai-sauchanka** [alexmingoia/koa-router#100]
It would be great to have an ability to make a route from path and data without creating a router, e.g.: ```Router.url('/user/:id', {id: 1}) => /user/1```

it can be something like:
```javascript
Router.url = function (path, params) {
    return Route.prototype.url.call({path: path}, params);
};
```

**Comment by alexmingoia** [comment]
PR welcome

**Comment by alexmingoia** [comment]
#101
