### ISSUE TITLE
router.use() can't be applied to two router

### ISSUE THREAD

**Issue by zhaoyao91** [alexmingoia/koa-router#104]
as the following example, I'd like 'from-router1-use' only be appended to all router1's routes
and 'from-router2-use' only be appended to all router2's routes
but when I visit localhost:3000/b
I get 'undefined from-router1-use  from-router2-use  from-router1-/b '
which implies that the middleware apply to router1 affects all middleware below
__________________

var Router = require('koa-router');
var router = new Router();
var router1 = new Router();
var router2 = new Router();

router1.use(function*(next) {
    this.body += ' from-router1-use ';
    yield next;
});

router1.get('/a', function*(next) {
    this.body += ' from-router1-/a ';
});

router2.use(function*(next) {
    this.body += ' from-router2-use ';
    yield next;
});

router2.get('/b', function*(next) {
    this.body += ' from-router1-/b ';
});

router.use(router1.routes());
router.use(router2.routes());

app.use(router.routes());

**Comment by jus101** [comment]
Same issue here. At the moment I'm getting around it by using koa-mount:
```
app.use(mount("/auth", auth_router.routes()));
app.use(mount("/users", user_router.routes()));
```
but it's not ideal.

**Comment by alexmingoia** [comment]
Your example works fine. You're getting "undefined" because you're doing string concatenation when `this.body` is `undefined`. You cannot do '+=' unless the left-side variable is already a string.

**Comment by jus101** [comment]
@alexmingoia correct me if I'm wrong, but I think the issue is that router1 middleware is running unexpectedly for router2 routes. Here's another example:
```
"use strict";

let koa = require("koa");
let users_router = require("koa-router")();
let auth_router = require("koa-router")();

let ensure_auth = function *(next) {
  console.log("Checking auth");
  yield next;
}

let get_user = function *(next) {
  console.log("Getting user");
  this.state.user = {name: "Jimmy"};
  yield next;
}

let app = koa();

users_router.get("/users/:user", function *(next){
  this.body = this.state.user;
});

auth_router.get("/token", function *(next) {
  this.body = 123123;
});

users_router.use(get_user);
auth_router.use(ensure_auth);

app.use(auth_router.routes());
app.use(users_router.routes());

app.listen(5000);
```
If you request http://localhost:5000/users/123 you'll see the following console output:
```
Checking auth
Getting user
```
In this case, the 'ensure_auth' middleware used by auth_router is running for a route that is handled by users_router.

**Comment by alexmingoia** [comment]
I see the confusion. `router.use(middleware)` is sugar for `compose([middleware, router.routes()])`. Middleware mounted this way runs regardless of whether a route has matched or not. It does make more sense that `router.use()` would only run the middleware if the request matches any of the routes.. I'll see about changing that
