### ISSUE TITLE
Nested routers?

### ISSUE THREAD

**Issue by nicholaswyoung** [alexmingoia/koa-router#105]
How would I handle the case where I have a router that responds to:

```
/route/
/route/:id
```
...etc, and another router that I want to respond to:

```
/route/:id/xxxx
/route/:id/etc/:id2
```

Sure, I could put ```/route/:id/xxx/``` as a prefix everywhere in the nested router, but that seems a bit sloppy.

Maybe I'm missing something, but it seems this should be doable without moving to ```koa-resource-router```. Any insight is appreciated.

**Comment by mickhansen** [comment]
Would be great for reusing `.param` for nested routes aswell.

**Comment by nicholaswyoung** [comment]
@alexmingoia Any thoughts on this?

**Comment by alexmingoia** [comment]
Routers can be nested per say, but what you want is for a router to have its registered route paths prepended with the path from the parent router. I'm not sure how this would be implemented but the easiest way that comes to mind is to have a `new Router({ prefix: '/root/path' })` option to automatically prefix all registered route paths.

**Comment by nicholaswyoung** [comment]
@alexmingoia Cool. Would that route prefix example work with parameters?

So a router mounted with a prefix of ```/thing/:thing_id``` would have the param ```thing_id```?

**Comment by nicholaswyoung** [comment]
@alexmingoia In theory, [this is what I'm looking for](http://stackoverflow.com/questions/25260818/rest-with-express-js-nested-router). The code in this post isn't perfect, but I think it will help you understand what I'm proposing.

**Comment by nicholaswyoung** [comment]
@alexmingoia @mickhansen I just added this feature in a way that satisfies all of the above requirements:

* ```router.param()``` works as expected.
* It matches up with Alex's idea of passing ```Router({ prefix: '/etc' })```

I think we're good to go.

**Comment by mickhansen** [comment]
@nicholaswyoung Does it reuse .param from a "parent" or do you have to define it on the router with the prefix aswell? (Not that that's an huge issue but would be nice sugar).

**Comment by nicholaswyoung** [comment]
@mickhansen I'm not sure what you're looking for. You might try pulling the code I wrote in #107 to see if it does what you need.

**Comment by alexmingoia** [comment]
Nesting routers is supported now in `5.0.0`. See https://github.com/alexmingoia/koa-router#nested-routers

**Comment by mickhansen** [comment]
@alexmingoia That's great, do they inherit the route `.param` aswell?

**Comment by alexmingoia** [comment]
@mickhansen Yes they will inherit `.param` logic. I did just fix a bug with missing parent parameters in `this.params` when using nested routers, so be sure you're on `5.0.1`.

**Comment by nicholaswyoung** [comment]
This is wonderful. Thanks @alexmingoia!
