### ISSUE TITLE
Routing override

### ISSUE THREAD

**Issue by nomadster** [alexmingoia/koa-router#106]
Hi, we have a structure built on top of koa and an old version of koa-router which basically, at startup time, loads a series of module each of which defines a routing file.

If you load module B after module A, and both request to register for a `GET /test` routing, what will happen in the current implementation is that module B's middleware overwrite module A's.

This happens for two reasons:
1. We do not inject the `next` parameter, so no middleware could do `yield next`. 
2. When B routing gets registered we basically do app.verb(path, newmiddleware).

The first has been fixed. For the second I have some doubt.
Let's take a look at this example
```js
var app = require('koa')(),
    router = require('koa-router')();
var Amiddleware = function*(){
	console.log('I am A middleware');
	this.body=42;
};

router.get('/test',one);
app.use(router.routes())
   .use(router.allowedMethods());
var server = require('http').Server(app.callback());
server.listen(8080);
```
What I want to do is something like, before registering router to koa with ```app.use(router.routes());```
```js
var Bmiddleware = function*(next){
	console.log('I sit on top');
	yield next;
};
//something like give me the koa-composed middleware for the verb V and path P
var oldMiddleware = router.getMiddleware('get', '/test'); 
router.get('/test', Bmiddleware, oldMiddleware);
```

What i expect as output, when i do `GET /test` is to have `42` as response and have the server print
```
I sit on top
I am A middleware
```

Is this possible? Am I missing any method?

**Comment by alexmingoia** [comment]
You shouldn't be registering the same route more than once. Why are you doing this? Ideally, `koa-router` would throw an error in that case.

If you want to replace a route you've already registered you'll need to loop through `router.stack.routes` to find the route you want and remove it from that array.

**Comment by nomadster** [comment]
Since who designed the micro framework we are using thought this was a good idea.
I was just wondering if there's at least a way to improve that behavior, but that's a no :)

Thanks
