### ISSUE TITLE
Typed named routes ? 

### ISSUE THREAD

**Issue by whosesmile** [alexmingoia/koa-router#109]
I was deploying a b2c website, In my project, the code next will return a  goods detail page:
`app.get('/shopping/:id', gen)`
and this will return customer cart:
`app.get('/shopping/cart', gen)`

the first middleware will be called when I request '/shopping/cart', I can write some code to validate id whether it's a int, and then yield next, but I think the code is ugly,  and I wish I can do this like python flask
```
@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post %d' % post_id
```
Maybe in koa-router, it can be:
`app.get('/shopping/<Number:id>', ''')`

**Comment by alexmingoia** [comment]
You can use https://github.com/alexmingoia/koa-router#module_koa-router--Router#param to do validation of parameters. You can also use regular expression route patterns to validate whether something is numeric.
