### ISSUE TITLE
Why does this.status = 404 turn into 405?

### ISSUE THREAD

**Issue by greergan** [alexmingoia/koa-router#112]
Hi,

I am curious why setting this.status = 404 is filtered to return a 405 error instead?

Thanks

**Comment by alexmingoia** [comment]
A 405 is returned if a route matched the path but not the method. Can you paste an example of the code that reproduces this?

**Comment by greergan** [comment]
I want to return a 404 status from my API when a resource is not found. I am setting the status like this.

this.status = 404;

in router.js on line 361 the 404 status gets explicitly filtered into a 405 status. I was just wondering why?

here is the block from router.js

    if (!this.status || this.status === 404) {
      this.matched.forEach(function (route) {
        route.methods.forEach(function (method) {
          allowed[method] = method;
        });
      });

**Comment by aesopwolf** [comment]
I'm having the same problem. Example code:

```js
app.get('/404', function* () {
  this.status = 404;
  this.body = "Not found";
});
```

**Comment by greergan** [comment]
Thank you very much.
