### ISSUE TITLE
[HELP] Issue Protecting Routes

### ISSUE THREAD

**Issue by MarkHerhold** [alexmingoia/koa-router#117]
Hi, I am new to using koa-router (and Koa) and am having a difficult time understanding how to protect routes using middleware while using koa-router. My "auth middleware" never seems to get called. Could someone please point out what I am doing wrong?

### Expected:
GET /api/public -> "hi from a public route"
GET /api/private -> some sort of 405 method not allowed or similar. I also expected to see `fake auth layer says you may NOT pass` in my logs.

### Actual
GET /api/public -> "hi from a public route"
GET /api/private -> "hi from a private & protected route". There is **no** message from my fake auth middleware.

### Sample Code
```javascript
var koa = require('koa');
var router = require('koa-router');

// init the app
var app = koa();

app.use(function*(next) {
	console.log('hi from middleware!');
    yield next;
});

// init the router
app.use(router(app, {
	prefix: '/api'
}));

app.get('/public', function*(next) {
    console.log('hi from a public route');
    this.body = 'hi from a public route';
});

// fake auth layer
app.use(function*(next) {
	console.log('fake auth layer says you may NOT pass');
	// yield next;
});

app.get('/private', function*(next) {
    console.log('hi from a private & protected route');
    this.body = 'hi from a private & protected route';
});

app.listen(3000);
console.log('app started');
```

**Comment by alexmingoia** [comment]
Make sure you're on 4.2.3 and let me know if you're still experiencing this issue. There was an issue with middleware order in 4.3.0

**Comment by MarkHerhold** [comment]
I am on 4.3.2 (which is probably what you meant to type). I made a brand new project just to test this.

I just checked node_modules/koa-router/ and the package.json there shows 4.3.2 as the version, so I am positive that I am on 4.3.2.

**Comment by alexmingoia** [comment]
I think the problem is that you're mounting the router before your authorization middleware. So the router middleware runs first, which matches your /private route and responds before reaching your authorization middleware.

**Comment by alexmingoia** [comment]
Unrelated but you can create a separate router for public and private routes which might make things easier to manage.

```javascript
var koa = require('koa');
var Router = require('koa-router');

var publicRouter = new Router({
  prefix: '/api'
});
var privateRouter = new Router({
  prefix: '/api'
});

publicRouter.get('/public', ...);
privateRouter
  .use(authorizationMiddleware)
  .get('/private', ...);

var app = koa();

app
  .use(publicRouter.routes())
  .use(privateRouter.routes())
  .use(publicRouter.allowedMethods());
```

**Comment by MarkHerhold** [comment]
You answered the question I was about to ask about the public/private route approach. I'll give that code a shot, thanks.

**Comment by MarkHerhold** [comment]
Thanks! That works perfectly!
