### ISSUE TITLE
Similar to the express routing framework

### ISSUE THREAD

**Issue by lglie** [alexmingoia/koa-router#119]
hi,
 I want in my app.js file written like this:
 var app=require('koa')();
 var router=require('koa-router');
 app.use('path', require('another file');//route to another js file

I want in my another file written like this:
 var koa=require('koa');
 var router=koa.Router(); //like express
 router.verb=function*(){....}

I don't know how to achieve.
 can you help me? 
 thinks!
 my email: 532875676@qq.com

**Comment by alexmingoia** [comment]
routes.js
```javascript
var Router = require('koa-router');
var router = require('./router.js');

router.get('/test', function *(next) {...});

module.exports = router;
```

app.js
```javascript
var koa = require('koa');
var router = require('./routes.js');

var app = koa();
app.use(router.routes());
app.use(router.allowedMethods());
```

**Comment by lglie** [comment]
sorry, I mean: 

koa-app.js:
var koa=require('koa');
var router=require('koa-router');
(How to write code?)

app.js:
var app=require('./koa-app');
app.use('/abc', require('b'));     //route to b.js page
app.get('/', function*(next){...}

b.js:
var router=require('./koa-app').Router();
router.get('/',function*(next){...};         //route: /abc
router.get('/xyz', function*(next){...};   //route: /abc/xyz
