### ISSUE TITLE
Nesting Routers is broken

### ISSUE THREAD

**Issue by smcmurray** [alexmingoia/koa-router#121]
module.exports = require('koa-router')()
.all('/user', require('./user/router'));

breaks at koa-router/node_modules/path-to-regexp/index.js:147
  return path.replace(PATH_REGEXP, replace);

where require('./user/router') returns a koa-router Router.

**Comment by smcmurray** [comment]
Issue #105 suggests that new Router(...) will allow nesting, but nothing in any documentation explains the difference between:

````
var router = require('koa-router')();
````
and
````
var router = new (require('koa-router'))();
````
or whether it needs to be
````
var router=new(require('koa-router')())();
````

**Comment by smcmurray** [comment]
From the source code, it looks like
````
new (require('koa-router'))();
````
is the same as
````
require('koa-router')();
````

**Comment by smcmurray** [comment]
````
module.exports = require('koa-router')()
  .all('/dept', require('./dept/router').routes());
````
produces a 404 for GET /dept/

when /dept/router looks like:
````
(function(){
  "use strict";

  modules.exports = require('koa-router')()
  .get('/', function *(){
    // Display list of departments
  });
}());

**Comment by RamIdeas** [comment]
I think I encountered a similar problem. I got around it by passing the koa app to a function which handles adding all the routers from different files.

``` js
module.exports = function applyRoutes( app ) {
    app.use( require('./dept/router/').prefix('/dept').routes() );
}
```

I actually index the routers in a prefix:router key:value'd object literal and then loop through the entries and run the `app.use` line above

**Comment by alexmingoia** [comment]
Nesting routers is now supported in `5.0.0`, so you can do something like `router1.get('/users', router2.routes())`. See https://github.com/alexmingoia/koa-router#nested-routers
