### ISSUE TITLE
4.3.0 => 4.3.2 Broke my code

### ISSUE THREAD

**Issue by BDiehr** [alexmingoia/koa-router#122]
Hi! I ran into an issue I can't seem to figure out. Below is a trimmed down version of what I have in my code base. Everything was running fine until I upgraded to 4.3.2. Any help would be greatly appreciated, thanks!

```javascript
 let Router = require('koa-router')

  /**
   * Controllers
   */

  ,   userController = require('../api/controllers/user')
  ,   projectController = require('../api/controllers/project')

  /**
   * Services
   */

  ,   authorizeUser = require('../api/services/authorizeUser')
  ,   fetchAccount = require('../api/services/fetchAccount')
  ,   fetchProject = require('../api/services/fetchProject')
  ,   updateToken = require('../api/services/updateToken');

  /**
   * Create routes
   */

  let userRoute = new Router();
  let projectRoute = new Router();

  /**
   * User middleware
   */

  userRoute.use(authorizeUser());
  userRoute.use(updateToken());

  /**
   * User routes
   */

  userRoute.get('/user', userAuthorizationController.getToken);
  userRoute.post('/user/password', userAuthorizationController.changePassword);

  /**
   * Project Middleware
   */

  projectRoute.use(authorizeUser());
  projectRoute.use(fetchAccount());

  /**
   * Project routes
   */
  projectRoute.get('/project/:projectId/team', projectController.getAll('teams'));

  /**
   * Initialize routes with the application
   */

  app.use(userRoute.routes());
  app.use(projectRoute.routes());
```

**Comment by alexmingoia** [comment]
What is the error or what is not working? That code looks fine.

**Comment by BDiehr** [comment]
Hi Alex, I appreciate your quick response! There are a number of routers I create (only showing userRoute and projectRoute in the above).

The only route which is still working is the first route which i register (not shown in the above code): `app.use(publicRoute.routes())` 

The remaining routes all result in 404 errors.

Thanks for the help! It's greatly appreciated.

**Comment by alexmingoia** [comment]
Are you still having trouble? You might not be yielding `next` if you subsequent middleware isn't running. Upgrade to `5.1.2` and let me know if you're still having issues.

**Comment by BDiehr** [comment]
Hi Alex,

Thanks for your reply, I have upgraded to `5.1.2` and it works!

It seems older versions have an issue where if you use middleware on a route, i.e.

```
  router.use(middlewareOne());
  router.use(middlewareTwo());
```

If in `middlewareOne` you do not `yield next`, it still traverses through the middleware.

But everything works as expected now!
