### ISSUE TITLE
example of using a separate routes.js file?

### ISSUE THREAD

**Issue by chovy** [alexmingoia/koa-router#125]
I want to separate out my routes based on endpoint.

I typically would do this in express:

./routes.js

-> loads ./api/things/index.js which has routes for `/api/things/*`

I can't figure out how to do something similar with koa-router. I have a SO if anyone wants to respond:

https://stackoverflow.com/questions/30285683/how-can-i-split-my-koa-routes-into-separate-files

**Comment by alexmingoia** [comment]
app.js
```javascript
var app = require('koa')();
var api = require('koa-router')();
var user = require('./routes/user');

api.use('/users', user.routes());

app.use(api.routes());
```

routes/user.js
```javascript
var router = require('koa-router')();

// responds to /users and /users:id
router
  .get('/', function *(next) {...})
  .post('/', function *(next) {...}})
  .get('/:id', function *(next) {...});

module.exports = router;
```

**Comment by chovy** [comment]
can we add to wiki or docs?

**Comment by paglias** [comment]
@alexmingoia I'm having some problems getting this to work:

routes.js
```js
var router = require('koa-router')();
//router.prefix('/api');

var controllers = ['users'];

controllers.forEach(function(controller){
  controller = require('../controllers/' + controller);

  router.use('/users', controller.routes());
});

// TODO allowed methods?
module.exports = router.routes();
```

controllers/users.js
```js
var router = require('koa-router')();

router.get('/me', function *getUserHandler(){
  this.status = 200;
  this.body = 'me';
});

module.exports = router;
```

I get a 404 if I try to get `/users/me`

**Comment by paglias** [comment]
even more simplified:

```js
var router = require('koa-router')();
var users = require('koa-router')();

users.get('/me', function *(next){
  this.body = 'me';
});

router.use('/users', users.routes());

// TODO allowed methods?
module.exports = router.routes();
```

**Comment by paglias** [comment]
Debugging shows:

```
info: App listenting on port 3333.
  koa-router GET /users/me +986ms
  koa-router test /users /^\/users(?:\/(?=$))?(?=\/|$)/i +1ms
```

**Comment by ysle** [comment]
or a bit more minimal approach :

app.js
```javascript
var app = require('koa')()
.use(require('./routes/user'))
.listen(80)
```

routes/user.js
```javascript
module.exports = require('koa-router')()
    .get('/user', function*() {
        this.body = 'user root'
    })
    .get('/user/:id', function*() {
        this.body = 'hello user ' + this.params.id
    })
    .routes()
```

**Comment by House3272** [comment]
I just came across this issue myself, how would one add in dependencies such as a database module or passport to @ysle 's example?

Thanks!

**Comment by ysle** [comment]
The passport thing should be separated. You may want to store some basic user specific data there, than you can access it easily like this `this.passport.user.name`

regarding the db, let's have mongoose as an example : 

```
.get('/api/users', function*() {
  this.body = yield User.find({})
})
```

where the User is your mongoose model as : 
`var User = require('../models/user')`

of course these above isn't for production use, just as an example. hope it helps a bit at least.

**Comment by House3272** [comment]
Getting there haha, thanks.

After separating out passport(or any other dependencies), should the route file have it as a direct dependency, or should the app.js file import it and pass it as an argument during the require for the route?
```

var router = require('koa-router');
module.exports = function( passport ) {
	router.get('*', function *(next) {
		passport.something;
	});
};
```

vs

```
var router = require('koa-router');
var passport = require('koa-passport');
router.get('*', function *(next) {
	passport.something;
});
exports.route = router;
```

**Comment by bidipeppercrap** [comment]
> app.js
> 
> ```js
> var app = require('koa')();
> var api = require('koa-router')();
> var user = require('./routes/user');
> 
> api.use('/users', user.routes());
> 
> app.use(api.routes());
> ```
> 
> routes/user.js
> 
> ```js
> var router = require('koa-router')();
> 
> // responds to /users and /users:id
> router
>   .get('/', function *(next) {...})
>   .post('/', function *(next) {...}})
>   .get('/:id', function *(next) {...});
> 
> module.exports = router;
> ```

How about seperate the `user` controller?
so we only need to import `api` without poluting app.js with controller.
