### ISSUE TITLE
Get /*

### ISSUE THREAD

**Issue by rrkhissamov** [alexmingoia/koa-router#126]
Hello everyone! Please help me.

If you use express I did so app.get('/*'). All requests method GET that were not clearly established router redirect to app.get('/*').

How do I implement it here? use koa-router and router.get('/*')

Thank you!

**Comment by coderhaoxin** [comment]
```js
app.get('/(.*)')
```

**Comment by alexmingoia** [comment]
I would strongly recommend against doing this. You should be using a catchall middleware mounted after the router to deal with 404s. For redirects you can use `router.redirect()`.

**Comment by ide** [comment]
I use multiple routers, one for API endpoints and another for website endpoints, and I'd like the 404 handler for the two to be different. By using a separate router for API endpoints, I can set up API-only middleware that ensures the response is formatted correctly which is awesome.

So the code I want to write is:
```js
var apiRouter = router({ prefix: '/api' });

apiRouter.use(someApiMiddleware());
apiRouter.get('/action1', ...);
apiRouter.get('/action2', ...);
apiRouter.get('/(.*)', apiEndpointNotFoundHandler);

app.use(apiRouter.routes());
app.use(apiRouter.allowedMethods());

var webRouter = router();
...
```

This keeps all the API-related code together in one coherent piece. With catch-all middleware outside of the router, I'd have to have it check for the "/api" path prefix and explicitly run `someApiMiddleware` again so the `/(.*)` path in the apiRouter is really helpful.

**Comment by bobiblazeski** [comment]
router.get('/(.*)', ....) catches all the routes, is there a solution that catches only routes that don't are not specified before?

**Comment by bobiblazeski** [comment]
I've settled on this for now
`````
app.use(routes);
app.use(serve(__dirname+'/../public'));
app.use(function *(next){
  if(this.status === 404 && this.accepts('html')){
    yield notFound.call(this);
  } else {    
     yield next;
  }
});
````````
