### ISSUE TITLE
Regex parameters

### ISSUE THREAD

**Issue by DanPantry** [alexmingoia/koa-router#127]
Is there any support for parameter matching using regular expressions? For example, something like this:

````javascript
router.get(/^foo\/(?param[A-z]*)\/baz$/, function *(param) {
  console.log(param);
});
````

`foo/qux/baz` would then print out `qux` to the console, but `foo/0/baz` would be ignored.

**Comment by alexmingoia** [comment]
Regular expressions are not supported. Supporting them makes diffing and concatenation of route paths too complex (used for nesting routers, prefixing, etc.). Also, in the future I plan on optimizing the route matching by using a trie hash, at which point regex's won't be used internally at all.

I suggest using `.param()` for parameter validation:

```javascript
router
  .param('bar', function *(bar, next) {
    if (!bar.match(/[A-z]+/)) {
      return this.status = 404;
    }
    yield next;
  })
  .get('/foo/:bar/baz')
```

**Comment by hbakhtiyor** [comment]
hi @alexmingoia, still not supported?

**Comment by danpantry** [comment]
@hbakhtiyor Looking back on this request I think it wasn't a great idea. There's almost certainly a better way to achieve what you want to do. What problem do you need to solve that requires regex routes?

**Comment by hbakhtiyor** [comment]
a bit like yours, but make some param is optional
e.g. 
`foo/qux.baz` and make `.baz` is optional

**Comment by danpantry** [comment]
This project uses `path-to-regexp` for its route matching, so you can use optional parameters without regex.

`foo/qux.:(baz)?`

https://github.com/pillarjs/path-to-regexp

This issue should remain closed as the router itself doesn't apply much special logic to paths.
