### ISSUE TITLE
5.1.0 reverses matching order

### ISSUE THREAD

**Issue by novacrazy** [alexmingoia/koa-router#131]
So for my application I have various routes that overlap somewhat, but I have them ordered in such a way that before version 5.1.0 it would pick the first matching route and run it. I even had it hooked up to a priority queue to add all my routes according to priority.

After 5.1.0 I noticed routes were always going to the last-added matching route, breaking my app completely. I simply reversed the priority queue and found that everything worked fine again.

However, the previous behavior of first-added, first to be chosen as a match seems to be more in line with the idea of a router, rather than having it choose the last match to run.

Would it be possible to revert or fix this behavior?

**Comment by alexmingoia** [comment]
Do you have an example of the code? The code that matched routes did not change in that release.

**Comment by novacrazy** [comment]
Yeah, of course.

Here is a simplified excerpt from my application, with the specific routes that overlap somewhat.
```javascript
router.get( 'user_page', '/user/(.*).jsx', function*(next) {
    if( this.state.authenticated ) {
        //Limits number of devices that can be logged into at once
        let AuthLimitController = yield this.controller( './controllers/auth/limit' );

        if( yield AuthLimitController( this.user ) ) {
            this.body = yield this.render( this.path );
            this.type = 'text/html';

        } else {
            this.logout();
            this.redirect( '/index.jsx' );
        }

    } else {
        this.redirect( '/index.jsx' );
    }
} );

router.all( 'app', '/app/(.*).jsx', function*(next) {
        //lengthy code that generates the client-side application script
} );

router.all( 'view', '(.*).jsx', function*(next) {
        this.body = yield this.render( this.path );
} );
```

Notice how the last one is sort of a catch-all for anything else. 

Before 5.1.0 the url `/user/account.jsx` would have matched the first route and `/app/user/account.jsx`would have matched the second. After 5.1.0, though, all `*.jsx` urls were matched with the last route no matter what, as if they were never even tested against the others. This was temporarily fixed by reversing the order they were added. 

So to get it to work with version 5.1.0 it's ordered like this:
```javascript
router.all( 'view', '(.*).jsx', ...);

router.all( 'app', '/app/(.*).jsx', ...);

router.get( 'user_page', '/user/(.*).jsx', ...);
```

However, I have quite a few non-overlapping routes in between all those, so simply reversing the order everything is added in is actually a bit annoying. So for now I've just reverted to version 5.0.1

**Comment by novacrazy** [comment]
Well that was fast. Thank you :smile:
