### ISSUE TITLE
suggestions for limiting .param usage to specific paths?

### ISSUE THREAD

**Issue by babsonmatt** [alexmingoia/koa-router#133]
Hey, just curious if there's a recommended way to use the param method for just a few specific paths?  Also wondering if it'd be worthwhile supporting arrays of paths for router.use?

Thanks!

**Comment by alexmingoia** [comment]
Create your own param middleware instead of using `router.param()` and use it only on specific routes. Route middleware will have access to `this.params`.

 I'd accept a pull request for arrays of paths for `router.use()`.
