### ISSUE TITLE
Accessing this.params outside router

### ISSUE THREAD

**Issue by MopperigeKat** [alexmingoia/koa-router#134]
I've split my routes into separate files, however I cannot seem to access the params that way. I'm receiving the error `Error: get '/foo/:id': 'middleware' must be a function, not 'undefined'`. What am I doing wrong?

**app.js**
```javascript
var koa = require('koa');
var router = require('koa-router')();

var app = koa();

var foo = require('./routes/foo.js');

router.get('/foo/:id', foo.specific);

app.use(router.routes());
app.use(router.allowedMethods());

if (!module.parent) {
  app.listen(8080);
}
```

**routes/foo.js**
```javascript
exports.specfic = function *(id) {
  this.body = id;
}
```

**Comment by Foxandxss** [comment]
Could be that you exported `specfic` and you are using `specific` ? (Typo)

**Comment by MopperigeKat** [comment]
Made a mistake while dropping my code in here, sorry about that. I fixed the typo, but the actual error still persisted for some reason. 
Decided to recode the part and use `this.params` instead of the function parameter, and heck, it worked. Still don't know what I did wrong the first time, but I'm glad it works. 

Thanks for your contribution!
