### ISSUE TITLE
Nested router with prefix

### ISSUE THREAD

**Issue by tuvistavie** [alexmingoia/koa-router#135]
Hi,

There seem to be an issue with nested routes when using a prefix for the routes.
Here is a minimal sample code to reproduce the issue.

```javascript
'use strict';

const koa    = require('koa');
const Router = require('koa-router');

let app = koa();

let router = new Router({
  prefix: '/prefix'
});

let nestedRouter = new Router();

nestedRouter.get('/', function *() {
  this.body = 'nested';
});

router.get('/', function *() {
  this.body = 'root';
});

router.get('/nested', nestedRouter.routes());

app.use(router.routes());

app.listen(8888);
```

I would expect the path `/prefix/nested` to use the `nestedRouter` handler, but I get 404 instead. If I remove the route prefix, I have `/` and `/nested` working as expected.

The issue occurs with node 0.12 as well as iojs.

Thanks for your help.

**Comment by tuvistavie** [comment]
It it can help, here is the output I get when I enable debugging.

```
  koa-router defined route HEAD,GET / +0ms
  koa-router defined route HEAD,GET / +3ms
  koa-router defined route HEAD,GET /nested +2ms
  koa-router GET /prefix/nested +565ms
  koa-router test /prefix/ /^\/prefix(?:\/(?=$))?$/i +1ms
  koa-router test /prefix/nested /^\/prefix\/nested(?:\/(?=$))?(?=\/|$)/i +0ms
  koa-router dispatch /prefix/nested /^\/prefix\/nested(?:\/(?=$))?(?=\/|$)/i +1ms
  koa-router GET /prefix/nested +1ms
  koa-router test / /^(?:\/(?=$))?$/i +0ms
```

**Comment by lin33274** [comment]
This fix doesn't seem to work and even caused regression that `/nested ` doesn't work now.
I think the problem is not exposed by unite test code because the test used `use` instead of `get` in `forums.use('/forums/:fid', posts.routes());`

**Comment by RavenHursT** [comment]
@alexmingoia can we reopen this?  I'm seeing the same thing 2.5 years later on `7.2.1`

**Comment by RavenHursT** [comment]
@jbielick noticed that you've been active on similar tickets https://github.com/alexmingoia/koa-router/issues/266 & https://github.com/alexmingoia/koa-router/issues/244

**Comment by RavenHursT** [comment]
Hmmmm... apparently this works!  I'm just a dummy.. was using `await next` vs `await next()` 🤦
