### ISSUE TITLE
Support any character in param names

### ISSUE THREAD

**Issue by maxfrigge** [alexmingoia/koa-router#137]
When defining a route param that has a dash in it's name e.g. `/v1/shopping-cart/:shopping-cart` the router fails to parse `shopping-cart` as a parameter. 

The resulting regular expression is something like this:
`/^\/v1\/shopping-cart\/([^\/]+?)-cart(?:\/(?=$))?$/i`

Notice the `-cart` part which should not be included in the test.

I know that it's NOT valid to use dashes in JS variable names, but from a developers point of view it's very natural to use it in a route definition, when thinking URLs rather the JS paramters.

**Comment by alexmingoia** [comment]
`koa-router` currently uses [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp) which doesn't support that.

**Comment by maxfrigge** [comment]
Ok. I guess the easiest way would to leave things as they are and add a short note about it in the readme.

**Comment by alexmingoia** [comment]
I've added a note to the readme. I'm closing this because there are no plans to support a path-to-regexp implementation separate from path-to-regexp. I'd be open to replacing the dependency if someone were to submit a PR, though it would have to have feature parity with path-to-regexp.
