### ISSUE TITLE
How to Get at the Routes Table

### ISSUE THREAD

**Issue by dschinkel** [alexmingoia/koa-router#145]
I'm trying to unit test the routes I setup with get.  I don't now how to access the routes dictionary.  Lets say I defined a default route for path "/".  How the heck can I check for that defined path in my TDD tests using Chai Assert?  When I try Router.routes, routes is a function, not a dictionary so not sure how I can access my routes from the router instance after the routes are set with get().

**Comment by alexmingoia** [comment]
`router.stack` is an array of the route layers. You can also lookup a route by name using `router.route(name)`.
