### ISSUE TITLE
Nested Routers Not Working Anymore

### ISSUE THREAD

**Issue by sunjay** [alexmingoia/koa-router#148]
I'm using exactly the example from the documentation:

    const koa = require('koa');
    const Router = require('koa-router');
    const app = koa();
    
    var forums = new Router();
    var posts = new Router();
     
    posts.get('/', function *(next) {
      this.body = "/";
    });
    posts.get('/:pid', function *(next) {
      this.body = `/${this.pid}`;
    });
    forums.get('/forums/:fid/posts', posts.routes());
     
    // responds to "/forums/123/posts" and "/forums/123/posts/123" 
    app.use(forums.routes());
    
    console.log(`Started listening on port 3000`);
    app.listen(3000);

Going to `/forums/123/posts` or `/forums/123/posts/123` both result in "Not Found"

**Comment by alexmingoia** [comment]
`forums.get()` should be `forums.use()`

**Comment by sunjay** [comment]
According to the documentation it should be get: https://github.com/alexmingoia/koa-router#nested-routers

:(

**Comment by hardchor** [comment]
See https://github.com/alexmingoia/koa-router/pull/139
