### ISSUE TITLE
`router.url` with nested router

### ISSUE THREAD

**Issue by kemskems** [alexmingoia/koa-router#150]
Hi. In my koa app I have nested routers like so:
```javascript
// routes/site.js
const router = require('koa-router')();

router.get('site.login', '/login', function *() { /* do something */ });

module.exports = router;
```
```javascript
// routes/users.js
const router = require('koa-router')();

router.get('users.list', '/', function *() { /* do something */ });

module.exports = router;
```
```javascript
// app.js
const app = require('koa')();
const router = require('koa-router')();

const site = require('./routes/site');
const users = require('./routes/users');

router.use(site.routes());
router.use('/users', users.routes());

app.use(router.routes());
```
The issue is, in `app.js`, `router.url('users.list')` returns the correct url but `router.url('site.login')` returns an error. I think this is inconsistent. What is the correct way to implement nested routers with named routes?

Thanks!

**Comment by neVERberleRfellerER** [comment]
Try this:
`router.use('', site.routes());`
It is strange, but AFAIK it is only way.

**Comment by kemskems** [comment]
@neVERberleRfellerER yes, in the end I used that. It works since `router.use` checks if the first argument is a string and if so it will assume that this is a nested router. I'd say this is more like a hack than a solution but this still solves my problem nonetheless. Thanks!
