### ISSUE TITLE
Inherit middleware from parent route

### ISSUE THREAD

**Issue by umidbekkarimov** [alexmingoia/koa-router#151]
Hi, I am very new to koa, and can't find any answer or example to this case

I have current pattern

`/event/:eventId` - event router
`/activity/:id` - event activity router

Activity router is nested in event router.
Event router has `:eventId` `.param()` middleware in it, but it doesn't shared with activity router.

So i don't really know is it issue or designful simplification to make router more controllable

**Comment by alexmingoia** [comment]
Middleware should be properly inherited from parent routes when nesting routers in `5.2.0`. I've also added a test for it.
