### ISSUE TITLE
Middleware and route handlers take effect in the wrong order

### ISSUE THREAD

**Issue by JoshWillik** [alexmingoia/koa-router#153]
When I use a router like the following:

```js
var router = require( 'koa-router' )()
router.get( '/', function*(){
  console.log( 1 )
})
router.use( function*( next ){
  console.log( 2 )
  yield next
})
router.use( function*(next){
  console.log( 3 )
  yield next
})
```

the following prints when `/` is accessed

```
2
3
1
```

instead of
```
1
2
3
```

**Comment by alexmingoia** [comment]
As per the documentation, `router.use()` mounts middleware before the route callback. https://github.com/alexmingoia/koa-router#routerusepath-middleware---router

**Comment by JoshWillik** [comment]
My apologies for opening an issue about documented behaviour.

Though, if you are looking at tweaking the library design for 5.0 , bringing routing/middleware order in line with the way express handles routing/middleware would be much more intuitive and useful IMHO.

Thanks for the library :)

**Comment by alexmingoia** [comment]
I will admit it is confusing because of the same name.

The idea behind `router.use()` and router-level middleware is that they only run for routes defined by a specific router. You cannot achieve this with koa's or (correct me if I'm wrong) express' `.use()`. Trying to achieve the same functionality with koa-compose won't work because the middleware will always run regardless of the route. This makes it impossible to have two routers (for example, users and posts) that use different middleware.

**Comment by JoshWillik** [comment]
That's fair. I suppose I approached the project expecting to have one master router that did everything instead of several more focused routers for smaller tasks. I will try the multi router approach with this project and see how it works out.

Thanks for your patience and the quick response time :)

**Comment by thedillonb** [comment]
@alexmingoia, I know I'm resurrecting an old thread but it seems deceiving that a router's middleware does not execute in the order of declaration. For example, express' router will correctly produce @JoshWillik's original assumption:

```javascript
var express = require('express');
var app = express();

app.get('/', function (req, res, next) {
  console.log('1')
  next();
});

app.use(function(req, res, next) {
  console.log('2');
  next();
})

app.use(function(req, res, next) {
  console.log('3');
  next();
})

app.listen(3000);
```

This will walk through the middleware in order that it was defined within the router. 

```
1
2
3
```

What advantages does having the `router.use()` middleware execute before all route callbacks? It would seem to diverge from what the express router exhibits - although, you might weight that as a good thing or a bad.
