### ISSUE TITLE
Nested routers with router prefix responds with the status code 404

### ISSUE THREAD

**Issue by roshangade** [alexmingoia/koa-router#155]
I tried to explore the **[nested routers](https://github.com/alexmingoia/koa-router#nested-routers)** by adding the [router prefix](https://github.com/alexmingoia/koa-router#router-prefixes) in it, but it responds with the status code 404.

Here is working example without adding the router prefix:
```js
var forums = new Router();
var posts = new Router();

posts.get('/', function *(next) {...});
posts.get('/:pid', function *(next) {...});
forums.use('/forums/:fid/posts', posts.routes());
app.use(forums.routes());

```

And here is the nested routers with the router prefix, which is not working:
```js
var forums = new Router({
    'prefix': '/forums'
});
var posts = new Router({
    'prefix': '/:fid/posts'
});

posts.get('/', function *() {
    this.body = 'posts'
});
posts.get('/:pid', function *() {
    this.body = 'post'
});

forums.use(posts.routes()); // OR forums.use('/', posts.routes());

app.use(forums.routes());
```

Could you please suggest or help me here. Thanks in advance.

**Comment by neVERberleRfellerER** [comment]
Try this:
`forums.use('', posts.routes());`

**Comment by roshangade** [comment]
Thanks!

**Comment by kudos** [comment]
I just encountered this too, it's a bug imo.
