### ISSUE TITLE
Nested routers middleware order?

### ISSUE THREAD

**Issue by jpetitcolas** [alexmingoia/koa-router#156]
I got the following code: 

``` js
var app = koa();

var router = require('koa-router')();
router.use(function* (next) {
    console.log('Router middleware');
    yield next;
});

var subRouter = require('koa-router')();
subRouter.use(function* (next) {
    console.log('Subrouter middleware');
    yield next;
});

subRouter.get('/', function*() {
    this.body = 'Hello world!';
});

router.use('', subRouter.middleware());

app
    .use(router.routes())
    .use(router.allowedMethods());
```

When I go on `/` route, I got the following debug messages:

> Subrouter middleware
> Router middleware

I would expect the opposite order, as I registered the router middleware first. Is it the expected behavior? If so, have you any clue to reverse this order? 

My use case is quite standard: I got a main router in which I initialize a database connection through a middleware (setting it in a `this.dbClient` property). Then, my subrouters (one per API) initialize its model repository via another middleware, passing it the `dbClient` service. The repository is then in an attribute to factorize code between all CRUD methods.

**Comment by neVERberleRfellerER** [comment]
Problem is here
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L256
normal `use` is using `unshift`, but when used with nested router, it uses `push`. Replacing `push` with `unshift` fixes this.
However, there is bigger problem than this. when you use multiple subrouters, each with different middleware, this sentence from docs: `Only runs if any route is matched` is no longer true. When one subrouter matches, middlewares from all subrouter are run.
