### ISSUE TITLE
multiple middleware issue

### ISSUE THREAD

**Issue by mfchung** [alexmingoia/koa-router#158]
Hi,

I am trying to reproduce the following functionality that exists in express
```javascript
var app = require('express')();

app.get('/', function(req, res, next) {
	console.log('do validation, yay!, you are validated');

	next();
});

app.get('/', function(req, res, next) {
	console.log('give access to secrets');

	res.send('secrets');
});

app.listen(8080);
```

in koa:-
```javascript
var app = require('koa')();
var router = require('koa-router')();

router.get('/', function*(next) {
    console.log('do validation, yay!, you are validated');

    yield next;
});

router.get('/', function*(next) {
    console.log('give access to secrets');

    this.body = 'secrets';
});

app.use(router.routes());
app.listen(8080);
```

the 2nd routing middleware never gets called.

I know I can define multiple middleware with koa-compose, but if I were building an API server I would have to build the validation into every path.

Is there another way to do this?

**Comment by neVERberleRfellerER** [comment]
Replace first `router.get` with `router.use`.

**Comment by alexmingoia** [comment]
You can use multiple callbacks or `router.use()` as suggested above.

```javascript
route.get('/', validationMiddleware, function *(next) {...});
```

`koa-router` should throw an error when you try to define multiple routes with the same path.
