### ISSUE TITLE
[Question] using router to catch all methods

### ISSUE THREAD

**Issue by chentsulin** [alexmingoia/koa-router#160]
In express v4, I usually use `app.use` or `router.all()` to catch all method `GET`, `POST` ...etc.

But when using `koa-router`, I can't find a approach to get this done.

```
var app = koa();
var router = new Router();

router.use('/foo/bar', function *(next) {
   this.body = {
      foo: 'foo'
   };
});

app.use(router.routes());
request(http.createServer(app.callback()))
  .get('/foo/bar')
```

something like this will got 404.

`Error: expected 200 "OK", got 404 "Not Found"`

I can just list all of them like below:

```
router.get('/foo/bar', myMiddleware);
router.post('/foo/bar', myMiddleware);
// ..
```

But It seems not a good enough answer. Any ideas here?

**Comment by alexmingoia** [comment]
You can use `router.all()`.

**Comment by ilaipi** [comment]
`router.all()` not in the documents.
