### ISSUE TITLE
how to handle one request in two router

### ISSUE THREAD

**Issue by Dongss** [alexmingoia/koa-router#164]
```
router.all('*', function * (next) {
    this.body = 'hello world';
});

router.all('*', function * (next) {
    this.body = 'bye world';
});
```
I get  'hello world'
can not put them in two? 

```
router.all('*', function * (next) {
    this.body = 'hello world';
    yield next;
    this.body = 'bye world';
});
```
then , I get 'bye world'

**Comment by divmgl** [comment]
In the first example, Koa is matching the first registered route.

In the second example, you are yielding somewhere but eventually the execution will return and overwrite your existing body...

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators
