### ISSUE TITLE
Multiple middleware

### ISSUE THREAD

**Issue by Phieo** [alexmingoia/koa-router#165]
```
router.get(
  '/users/:id',
  function *(next) {
    this.user = yield User.findOne(this.params.id);
    yield next;
  },
  function *(next) {
    console.log(this.user);
    // => { id: 17, name: "Alex" }
  }
);
```
When ```User.findOnde``` is async,  
such as mongoose, which data is returned in a callback,
```
User.findOnde({_id: id}, function (err, user) {
    
})
```
 is there a solution to handle the problem?

**Comment by alexmingoia** [comment]
No clean solution to this at all if you're using mongoose. You'll have to wrap mongoose to return thunks/promises or find a module that does so.

**Comment by Phieo** [comment]
@alexmingoia, thanks, I get it.
