### ISSUE TITLE
Question on multiple-middleware 

### ISSUE THREAD

**Issue by fansgit** [alexmingoia/koa-router#168]
Tested [multiple-middleware](https://github.com/alexmingoia/koa-router#multiple-middleware) below, Why was only the last middelware triggered to print out `world`?

```javascript
router.all(
  '*',
  function *() {
    console.log('Hello ')
  },
  function *() {
    console.log('world')
  }
);
```

**Comment by divmgl** [comment]
You're not calling `yield next`.

**Comment by fansgit** [comment]
@divmgl I got the same result below - the first middleware wasn't called at all.

```javascript
router.all(
  '*',
  function *(next) {
    console.log('Hello')
    yield next
    console.log('Hello again ')
  },
  function *() {
    console.log('world')
  }
);
```
Test with [koa](https://github.com/koajs/koa) below printed out everything as expected.
```javascript
app.use(
  function *(next) {
    console.log('Hello')
    yield next
    console.log('Hello again')
  }
);
app.use(
  function *() {
    console.log('world')
  }
);
```

**Comment by divmgl** [comment]
Works for me.

https://gist.github.com/divmgl/5f3afcbe641515ab4613

**Comment by fansgit** [comment]
@divmgl  thanks, now it works for me, too. The previous problem was caused by a syntax error on my livescript version.
