### ISSUE TITLE
koa-router doesn't support Cross Domain request?

### ISSUE THREAD

**Issue by freestyle21** [alexmingoia/koa-router#171]
here is my code:
        
        app.get('/path/', function *(next) {
            this.redirect('https://www.google.com');
         });

but the browser say `XMLHttpRequest cannot load https://www.google.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:3001' is therefore not allowed access.`

or is there any solution to redirect in our router function.

Thanks for you reply.

**Comment by sinkingshriek** [comment]
I don't think is particularly `koa-router`'s issue. 
It has mostly to do with `same-origin policy` by your web-browser. You can allow cross domain on your server by doing:-

```
app.use(function *(){
this.set('Access-Control-Allow-Origin', '*');
});
```
before your all your routes.   
Do note that this will allow any site to make request on your resource. To restrict only your domain you can also do:-
```
this.set('Access-Control-Allow-Origin'. 'http://localhost:3000');
```
_Disclaimer: haven't really tested the code_

**Comment by AllenFang** [comment]
it's not about <code>koa-router</code>, you can take <a href="https://github.com/koajs/cors">koa-cors</a> a look, it will help you.

**Comment by kirkstrobeck** [comment]
http://stackoverflow.com/questions/36328085/can-t-get-cors-working-with-koa
