### ISSUE TITLE
Use of application middleware

### ISSUE THREAD

**Issue by lukebennett** [alexmingoia/koa-router#172]
I'm coming back to koa-router after not using it for a couple of versions and can see there have been some significant changes - unfortunately I'm really struggling to get the fundamentals working and feel like I must be missing something obvious because I'm sure you can't have stopped supporting such a basic use case.

Here is a simplified version of what I used to do:

```javascript
app.use(function *() {
    this.foo = 'bar';
});

var router = new Router(app);
app.use(router.middleware());
app.get('/foo', function *() {
    console.log(this.foo);
});
```

What I'm having to do now is:

```javascript
app.use(function *() {
    this.foo = 'bar';
});

var router = new Router();
router.get('/foo', function *() {
    console.log(this.foo);
});
app.use(router.routes());
```

However `this.foo` does not exist within my route as `this` no longer refers to `app` but to `router`. The obvious solution would be to change `app.use` to `router.use` but that option isn't open to me as I need the middleware to remain on the app object for use elsewhere. Nor can I pass the same function into both `use` methods as in real life the middleware is not defined in the same place as the router - I don't have access to the latter where I would need it. I've tried dynamically reading the middleware off `app.middleware` and passing everything to `router.use` in one go but have been unable to get that to work.

How would you deal with this simple scenario? I'm really hoping you can show that I'm being stupid and that I won't need to dump koa-router.

**Comment by santialbo** [comment]
I think the prefered approach in koa is that you attach things to `this.state`. Within the middleware `this` doesn't refer to either the `app` or the `router` but to a "context" that is created for every request. Anyway the following logs `bar` correctly.

```js
var koa = require('koa');
var Router = require('koa-router');

var app = koa();
app.use(function *(next) {
  this.foo = 'bar';
  yield next;
});

var router = new Router();
router.get('/foo', function *() {
  console.log(this.foo);
});
app.use(router.routes());

app.listen(3000);
```

**Comment by lukebennett** [comment]
Thanks - I tracked down the issue, turned out to be middleware not running in the order I thought it was.
