### ISSUE TITLE
Nested routers with named routes

### ISSUE THREAD

**Issue by macprog-guy** [alexmingoia/koa-router#176]
In the examples, nesting routers essentially means including the child routers middleware into the parents. But by doing so we loose all the other meta-data associated with routes including things like named routes. Would it be possible to enhance the router with .use(path, router), which would include the child router layers as opposed to its middleware? Perhaps there is already a way to do this that I have not seen? Thanks for an otherwise excellent project.

**Comment by alexmingoia** [comment]
This is working in `5.2.0` and I've added a test for it.

**Comment by alexmingoia** [comment]
Please re-open if you're still experiencing an issue. The functionality you describe is already how koa-router works, if I understand you correctly.

**Comment by macprog-guy** [comment]
Thanks you and keep up the excellent work!
