### ISSUE TITLE
Example of ES6 usage of koa-router with babel transpiler?

### ISSUE THREAD

**Issue by egeland** [alexmingoia/koa-router#189]
Hi,

I'm still very much a JS / Koa beginner and I'm trying to learn ES6 (and ES7's cool async/await), but I don't really understand how I'm supposed to use the koa-router in the ES6/7 world, so hoping for some clues.

This starts a server (after transpiling with `babel --optional runtime`):
```js
import koa from 'koa';
import router from 'koa-router';

let koarouter = router();

koarouter.get('/', async function() {
    this.body = 'Hello World!';
});

var app = koa();
app.use(koarouter.routes());
app.listen(3000);
console.log('Listening on http://localhost:3000');
```

But is there a better way than that `let koarouter = router();` statement?

And I currently seem to need to use the `--optional runtime` argument with babel, am I doing it wrong?

**Comment by alexmingoia** [comment]
No, none of that is wrong. `--optional runtime` is required if you aren't requiring the regenerator in your application code.

**Comment by egeland** [comment]
Thanks for the confirmation! :smile:
