### ISSUE TITLE
How to Specify params in the URI via Name

### ISSUE THREAD

**Issue by dschinkel** [alexmingoia/koa-router#193]
I cannot get this to match:

    /people/locationId:12345

I've seen others out there do stuff like this /users/name:John/age:30

Notice yes, the colon is on the right side.   That's because I want to allow my callers to specify filter criteria in the uri itself.

Here was my attempt, my route definition, not sure what else to try, none of these attempts at creating the route work for me:

    /people/([a-z-]+)locationId:?
    /people/locationId([a-z-]+):?
    /people/locationId:?
    /people/:locationId:?

It does match this but only because the way this route is, it's a catch all that is able to take really any value.

'/people/:locationId?': { to: 'person#find' }

I can't use that especially when I have other routes defined such as:

'/people/:id': { to: 'person#findById' }

because it would hit this route, which is not the right route.

**Comment by alexmingoia** [comment]
Koa-router used the [path-to-regexp](https://github.com/pillarjs/path-to-regexp) module to translate path patterns into regular expressions.

The pattern string you want is `/people/:locationId(locationId:\\d+)`. That matches `/people/locationId:12345` and populates `ctx.params.locationId` with `locationId:12345`.

As far as I know, you cannot get just `12345` out of the parameter value without middleware. I would recommend creating your own query parsing middleware mounted to the router using `router.use()` that inspects `ctx.params.locationId` and removes the `locationId:` prefix from the value for subsequent middleware.
