### ISSUE TITLE
About sequence sensitivity

### ISSUE THREAD

**Issue by qt911025** [alexmingoia/koa-router#194]
Example

```javascript
fooRouter.post('/', function *() {
  console.log('create user');
  this.body = {foo: 'bar'};
});

fooRouter.use('/', function *(next) {
  console.log('check authentication');
  this.body = {foo: 'middle?'};
  return yield next;
});

fooRouter.put('/password', function *() {
  console.log('change password of a user');
  this.body = {foo: 'else?'};
});

fooRouter.put('/profile', function *() {
  console.log('change profile of a user');
  this.body = {foo: 'else?'};
});
```

When I request `GET /`, the code will run the second hook before the first hook, which is not like router of Express (When the first hook catches the route, It will not go through unless it yield next).
Is it designed to give a higher priority to "use" than methods?

**Comment by tjyrkinen** [comment]
I find this unintuitive as well.

As an example, what I would like to do is define a router for the REST API part of my application, /api. Most of the routes will require a user model to be available in the context, but not all. However, with the way the use takes precedence over verbs, I'm unable to define the sequence the way I need. It's not difficult to come up with other examples where the practical solution would be to rely on the order the handlers are defined.

**Comment by alexmingoia** [comment]
I agree it is confusing. It should be run in order specified. I will push a fix for this.

However, I don't understand @qt911025 or @tjyrkinen use cases. Don't you both want to run authentication and user population middleware *before* your route handlers?

**Comment by tjyrkinen** [comment]
Good to hear!

I did in fact get around this by introducing more nested routers but if an update on this isn't too difficult to implement it'd be the preferred way.

As to the use case I mentioned above, it was sensible for me to expose a part of a router (handling users in particular) for public use while the rest required authentication so I wanted to place the authentication middleware in between these sections.

**Comment by halleycarleton** [comment]
Is there any chance of getting this into  5.x?
