### ISSUE TITLE
router.use() defined functions unexpectedly mutate this.params context

### ISSUE THREAD

**Issue by Edward-Lombe** [alexmingoia/koa-router#196]
Here is the code to replicate the issue

```javascript
'use strict';

import koa from 'koa';
import Router from 'koa-router';

const app = koa();
const router1 = new Router({ prefix : '/router1'});
const router2 = new Router({ prefix : '/router2'});

router1.use('/', function* (next) {
  console.log('this.params', this.params);
  yield next;
});

router1.get('/', function* (next) {
  this.body = 'router1';
  yield next;
});

router2.use(function* (next) {
  console.log('this.params', this.params);
  yield next;
});

router2.get('/', function* (next) {
  this.body = 'router2';
  yield next;
});

app
  .use(router1.routes())
  .use(router1.allowedMethods())
  .use(router2.routes())
  .use(router2.allowedMethods())
  .listen(3000);
```

This code starts a simple server on port `3000` and listens under `/router1` and `/router2` respectively. The first router is fine, with `this.params {}` being logged each time a request is made. the problem seems to lie in `router2.use(function* ...`. This for some reason will log `this.params { '0' : '' }` to the console.

I've tested this under `node v4.2.1` under Windows and OSX 10.11 and they both have the same result.

Any idea what's going on here, or whether this is intended behaviour or not?

**Comment by alexmingoia** [comment]
This has been fixed in 7.x

**Comment by Edward-Lombe** [comment]
Thanks :+1:
