### ISSUE TITLE
Path in array breaks sometimes

### ISSUE THREAD

**Issue by mfchung** [alexmingoia/koa-router#197]
consider the following code 

```javascript
/*jshint node:true*/
/*jshint esnext:true*/
'use strict';

var publicRoutes = require('koa-router')();
var send = require('koa-send');

publicRoutes.get(['/app/pub/app.module.js'], function *(next) {
	yield send(this, this.request.url);
});

publicRoutes.get(['/app/pvt/com/*/*.js', '/app/pvt/com/*/*.html'], function *(next) {
	yield send(this, this.request.url);
});

publicRoutes.get(['/app/pvt/com/*/*.js'], function *(next) {
	yield send(this, this.request.url);
});
```
the first route throws an exception, the second and third works fine.

the exception is 

**/home/doc/Desktop/os1/node_modules/koa-router/lib/router.js:513
      var routeNestingLevel = route.path.split('/').length;
                                         ^
TypeError: route.path.split is not a function**

I am using version nodejs 4.2.1 and koa-router 5.2.3

**Comment by praveenax** [comment]
It got resolved when I used Koa-router:5.1.2.
