### ISSUE TITLE
How to cancel/unregister/re-register route mapping in runtime

### ISSUE THREAD

**Issue by ReDreamport** [alexmingoia/koa-router#200]
Hi,
How could I cancel/unregister/re-register route mapping at runtime? I mean:

1. Change the handler of an existing route mapping at runtime
2. Cancel or unregister route mappings, make them to return 404

**Comment by alexmingoia** [comment]
You would need to iterate `router.stack` and remove or modify the routes at runtime.

**Comment by adoyle-h** [comment]
I think it will be a good feature to register/unregister/toggle route at runtime. What do you think? @alexmingoia

**Comment by sartrey** [comment]
@alexmingoia Thanks!
`router.stack` is easy to operate & I've finished HMR by using it
maybe we should introduce this in readme?

**Comment by DanielHreben** [comment]
I also need this feature. Going to use `router.stack` since there is no public API, and hope it's shape not going to be changed in minor releases.
