### ISSUE TITLE
app.get is not a function

### ISSUE THREAD

**Issue by christiansakai** [alexmingoia/koa-router#204]
Hello,

I'm having a simple issue, but can't figure out how to fix this. I think I am doing it right. Using koa 1.1.2 and koa-router 5.2.3

Here is my code:
```
import Router from 'koa-router';

const app = koa();

// Centralized error handling
app.use(function *(next) {
  try {
    yield next;
  } catch (err) {
    this.response.status = err.status || 500;
    this.response.body = err.message;
    app.emit('error', err, this);
  }
});

app.use(new Router(app).middleware());

if (env === 'development') {
  app.use(morgan.middleware('dev'));

  /**
   * Webpack Related
   */
  app.get('/build/*', proxy({
    host: `http://localhost:${webpackPort}`
  }));
}
```

and here is the error
```
  app.get('/build/*', (0, _koaPixieProxy2['default'])({
      ^

TypeError: app.get is not a function
    at Object.<anonymous> (/Users/christiansakai/Desktop/cs/server/koa.js:36:7)
    at Module._compile (module.js:434:26)
```

**Comment by alexmingoia** [comment]
Use `router.get()` https://github.com/alexmingoia/koa-router#new-routeropts

**Comment by laggingreflex** [comment]
Some [tutorials] still use the old syntax. If this is really deprecated I think it should be mentioned in the readme. And the readme also mentions "Express-style routing using app.get, app.put, app.post, etc." 

[tutorials]: http://knowthen.com/episode-8-serving-content-in-koajs-with-marko/

**Comment by laggingreflex** [comment]
Btw I really liked using just `app.get`. Was this deprecated for a performance reason? 

I was thinking of reimplementing it myself by extending the Koa class like this:

    class KoaWrapper extends Koa {
        constructor(opts) {
            super(...arguments);
            this.router = Router();
        }
        get() {
            this.use(this.router.get(...arguments).routes());
        }
        // post() {...
    }

Would this be a terrible idea?
