### ISSUE TITLE
[Help] Middleware not work as expected when separate into multiple Routes

### ISSUE THREAD

**Issue by WangJi** [alexmingoia/koa-router#205]
At first, I wrote the code below in one file:
```javascript
var router = require('koa-router')();
router.use('/user/:id', function* (next) {
    this.state.user = User.getById(this.params.id);
    yield next;
});
router.get('/user/:id/action1', function* (next) { });
router.get('/user/:id/action2', function* (next) { });
```
In this way, `this.state.user` could be successfully passed to the lower middleware.

----------

Then for the purpose of easy maintenance, I split this file into several ones like:

**user.js**
```javascript
var router = require('koa-router')();
router.use('/user/:id', function* (next) {
    this.state.user = User.getById(this.params.id);
    yield next;
});
```

**user.action1.js**
```javascript
var router = require('koa-router')();
router.get('/user/:id/action1', function* (next) { });
```

**user.action2.js**
```javascript
var router = require('koa-router')();
router.get('/user/:id/action2', function* (next) { });
```
**app.js**
```javascript
app.use(user.routes());
app.use(user-action1.routes());
app.use(user-action2.routes());
```
Now, `this.state.user` **can not** get passed to the lower middleware, because the upper middleware `/user/:id` is never triggered.
Did I miss something here?

**Comment by alexmingoia** [comment]
Which version of koa-router are you using? I've added a test case for this and it is not an issue when tested against `7.0.0` and `koa-2.0.0-alpha.3`

**Comment by WangJi** [comment]
I'm trying on `koa@1.1.2` and `koa-router@5.3.0` with no success.
At last, I find a way to work around it by adding an additional router middleware. Use this router to **wrap** all the other routers.
In another word, all routers are **nested** under this unique middleware. 
So, the code in **app.js** can be written like this:


**app.js**
```javascript
var router = require('koa-router')();
router.use(user.routes());
router.use(user-action1.routes());
router.use(user-action2.routes());
app.use(router.routes());
```

Now, it works.
