### ISSUE TITLE
app.use() requires a generator function

### ISSUE THREAD

**Issue by airyland** [alexmingoia/koa-router#207]
``` javascript
var koa = require('koa');
var app = koa();
var router = require('koa-router')();
app.use(router.routes());
app.use(router.allowedMethods());
```

```
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: app.use() requires a generator function
    at Application.app.use (E:\workspace\node_modules\koa\lib\application.js:105
:5)
    at Object.<anonymous> (E:\workspace\iForm\index.js:13:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

```

**Comment by unbornchikken** [comment]
+1. 6.0.0 breaks my application. Iám using something leki the following with an exception:

```
var koa = require('koa');
var app = koa();
var router = require('koa-router')();
router.use("", myCoolMiddleware());
app.use(router.routes());
app.use(router.allowedMethods());
```

So I believe the problem is that, when there is no `get`, `post`, etc, just some `use`, then 6.0.0 doesn't provide a valid middleware for the `route` method.

**Comment by alexmingoia** [comment]
Are you using koa@2 ?

**Comment by wcastand** [comment]
Hi,
I have the same issue with the example code : 
```
var app = require('koa')();
var router = require('koa-router')();

router.get('/', function (ctx, next) {
  console.log("te")
});

app
  .use(router.routes())
  .use(router.allowedMethods());
```
i just install koa and koa-router in a new file. Adn the write the code in a server.js file.
I use Windows 10(x64) with npm 3.3.12 and node 5.1.0
I  get this :
```
assert.js:89
  throw new assert.AssertionError({
  ^
 AssertionError: app.use() requires a generator function
    at Application.app.use (F:\Web\test-koa\node_modules\koa\lib\application.js:105:5)
    at Object.<anonymous> (F:\Web\test-koa\server.js:9:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by wcastand** [comment]
The problem come from koa package.
When you npm install koa, he still install 1.1.2 to be sync with the website documentation. 
But the documentation and examples on github readme are for the version 2.

I don't know if it's an error or not but basic install with npm install on koa and koa-router should be sync with their documentation because i spend 2-3 hours trying examples from koa and koa-router lol

**Comment by sterling** [comment]
@alexmingoia is this documented anywhere? I'm trying to figure out why the latest koa-router is dependent on a version of koa that is not even released yet...

**Comment by alexmingoia** [comment]
See https://github.com/alexmingoia/koa-router#migrating-to-7--koa-2 and [koa 2](https://github.com/koajs/koa/tree/2.0.0-alpha.3#example).

**Comment by rally25rs** [comment]
@alexmingoia since Koa 2 is still in alpha (`npm install koa` downloads v1) it seems like this library should have been left in alpha too. Now users can no longer simply:

    npm install koa
    npm install koa-router

and expect it to work.

**Comment by alexmingoia** [comment]
Ah yes, you're right. I've set the `latest` npm dist-tag to 5.3.0 and `next` to 7.0.0.

**Comment by Moezalez** [comment]
I have the same issue with koa1.

```
 "koa": "^1.2.0",
 "koa-router": "^5.4.0"
```

`AssertionError: app.use() requires a generator function`

**Comment by Ge-yuan-jun** [comment]
I have met the same question.
My solution:
```
npm install koa-views@4.1.0

```
and,it works

**Comment by Tyguy7** [comment]
@Ge-yuan-jun you are correct, the latest version doesn't seem to be compatible with legacy node

**Comment by bobvanderlinden** [comment]
Same problem here with the simplest of usage with node v6.8.0:

```
yarn add koa koa-router
```

```
const app = require('koa')()
const router = require('koa-router')()

app.use(router.routes())

app.listen(3000)
```

What versions should be used for which library?

**Comment by watson** [comment]
@alexmingoia I think the `latest` dist-tag got set to v7 again. People who want to use this with the production version of Koa should now run `npm install koa-router@5 --save`

**Comment by kyasbal-1994** [comment]
This problem should resolved as soon as possible. `koa-router` is now almost mandatory module for using koa. So, this problem makes users prevent touch with koa.js.

**Comment by gensmusic** [comment]
still not fixed!!!!!!

**Comment by alexmingoia** [comment]
```sh
npm dist-tag ls koa-router
latest: 5.4.0
next: 7.0.1
```
