### ISSUE TITLE
How to pass an array of middlewares

### ISSUE THREAD

**Issue by Utkarsh85** [alexmingoia/koa-router#212]
Currently, koa-router supports multiple middlewares as comma separated generators. This is useful when I define the middlewares, when defining the route. But I have a scenario where multiple middlewares sit in other files and I have to define the route with an array of middlewares. How can this be done.

**Comment by kimmobrunfeldt** [comment]
Could you use Function.prototype.apply?

e.g. 
```js
var middlewares = [middle1, middle2];
var params = ['get'].concat(middlewares);
router.get.apply(this, params);
```

**Comment by Utkarsh85** [comment]
It doesn't work. Throws "TypeError: this.register is not a function" at "koa-router/lib/router.js:182". Meanwhile I found [compose](https://github.com/koajs/compose) which works fine this syntax
```javascript
var compose=require('koa-compose'); // I used koa-compose@2
var middlewares = [middle1, middle2];
router.get('/my/:path',compose(middlewares))
```

**Comment by tayste5000** [comment]
If Node v5.* is an option you can use the spread operator (...):

    router.get('/my/:path', ...middlewares)

**Comment by jbielick** [comment]
@Utkarsh85 

@kimmobrunfeldt 's answer will work, but the `this` context being passed is probably incorrect.

the example should look like this:

```
var middlewares = [middle1, middle2];
var params = ['/my/:path'].concat(middlewares);
router.get.apply(router, params);
```

**Comment by kimmobrunfeldt** [comment]
@jbielick Didn't realise that, thanks for the correction :)

**Comment by polRk** [comment]
This is doesn't working with 
```
const myMap = Map<string, Koa.Middleware<AppState, AppContext>>
router.use('/abc', ...myMap.values())
```
