### ISSUE TITLE
expose matched route

### ISSUE THREAD

**Issue by kunalgolani** [alexmingoia/koa-router#223]
Need to know in the common middlewares for all routes which route will finally be served. Couldn't find a way to do this.

**Comment by jergason** [comment]
I'd also like to know what route was matched (separate from the URL on the request) so I could access it  in a middleware for monitoring. Say I have some route like this:

```javascript
route.get('/foo/:id/:type', function*() { this.body = "ok" })
```

I'd like to be able to create a middleware like this:

```javascript
function* routeMetrics(next) {
  var start = Date.now()
  yield next
  var duration = Date.now() - start
  // send a metric
  statsd.timing(this.matchedRoute, duration)
  // this.matchedRoute would be the string of the matched route, so '/foo/:id/:type/' in this case
}

route.get('/foo/:id/:type', routeMetrics, function*() { this.body = "ok" })
```

**Comment by kunalgolani** [comment]
if you add another similar but more generic route, this._matchedRoute always gives the more generic route instead of the actually matched more specific one
```
router.get('/users/:id', function *() {
    // this._matchedRoute is '/:username/:id'
});
router.get('/:username/:id', function *() {
    // this._matchedRoute is '/:username/:id'
});
```
