### ISSUE TITLE
middleware executed after route callback no matter order

### ISSUE THREAD

**Issue by g13013** [alexmingoia/koa-router#229]
I am trying to execute a middleware before a route handler function gets called, but no matter the order, my middleware always gets called after.

version: `5.3.0`

I tried:
```js
this.router.use(`/${module}`, middleware);
this.router.use(`/${module}`, anotherRouter.routes());
```
```js
this.router.use(`/${module}`, middleware, anotherRouter.routes());
```
```js
this.router.use(`/${module}`, anotherRouter.routes(), middleware);
```

**Comment by amccloud** [comment]
Same for me

```javascript
async function requireAuth(next) {
  console.log('BEFORE');
  await next;
  console.log('AFTER');
}

router.post('/test', requireAuth, async function createDeployment() {
  console.log('POST');
});
```

This outputs:

> POST
> BEFORE
> AFTER

**Comment by amccloud** [comment]
Switching from async to generator solved my problem

**Comment by g13013** [comment]
I always used a generator

**Comment by xiaokekeT** [comment]
+1 But I want to use async what should I do

**Comment by alexmingoia** [comment]
If you want to use async you need to use koa@2 and koa-router@7. The reason for this is due to how babel transforms async code into generators, which causes problems for koa-router@5.
