### ISSUE TITLE
Async/Await and router.param() called in wrong order

### ISSUE THREAD

**Issue by fmatoss** [alexmingoia/koa-router#230]
When I use HTTP GET in /user/1 with generators:

```javascript
router
  .param('user', function* (id, next) {
    console.log(1);
    yield next;
  })
  .get('/users/:user', function* (next) {
    console.log(2);
  });
```

It outputs:
```
  <-- GET /users/1
1
2
  --> GET /users/1 404 7ms -
```

But with async/await:
```javascript
router
  .param('user', async function (id, next) {
    console.log(1);
    await next;
  })
  .get('/users/:user', async function (next) {
    console.log(2);
  });
```

It outputs:
```
  <-- GET /users/1
2
1
  --> GET /users/1 404 7ms -
```

I'm using koa v1.1.2 and koa-router v5.3.0

**Comment by alexmingoia** [comment]
To use async/await you need to be using koa 2 and [koa-router 7.x](https://github.com/alexmingoia/koa-router/tree/master/)

**Comment by fmatoss** [comment]
I saw the description "ES7 async/await support." in branches v5.x and master, so I thought it was supported in both versions. Thanks for clarifying!
