### ISSUE TITLE
koa-router 7 is not working with 3 async middlewares

### ISSUE THREAD

**Issue by Alex0007** [alexmingoia/koa-router#234]
Get code from [example](https://github.com/alexmingoia/koa-router/tree/master#multiple-middleware) and try to add another middleware with setTimeout inside

**Comment by jbielick** [comment]
Thanks for pointing this out, @Alex0007.

The example should be more clear. `next` must be called and added to the promise chain or `await`ed for the middleware stack to continue executing. Please see if [this commit](https://github.com/alexmingoia/koa-router/commit/7ff98ae8549534d357b264975018828e36be6ee1) and example in the commit message explains it sufficiently. If not, feed free to re-open this issue!
