### ISSUE TITLE
koa-router 5 doesn't support .use(RegExp, something.middleware())

### ISSUE THREAD

**Issue by asafyish** [alexmingoia/koa-router#235]
Getting this exception:
throw new Error(
            ^
Error:  `(.*)`: `middleware` must be a function, not `object`

Traced it to https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L230 which causes the handler function to be be lost.

**Comment by alexmingoia** [comment]
Regexp routes aren't supported. They break other features such as named route parameters, nested router composition, methods like `router.url()`, etc. Theoretically support is possible, but the work needed is extensive to deal with all the edge cases. We had a patch that was merged in a previous version, but it introduced a number of other bugs so support was dropped.
