### ISSUE TITLE
Allow middleware to be executed even when no route was matched

### ISSUE THREAD

**Issue by per2plex** [alexmingoia/koa-router#239]
I just started using `koa@2.x` together with `koa-router@7.x` and noticed that middlewares don't get executed if no defined route matches, coming from express this was kinda unexepected. I searched if this was by design because even examples in the README don't seem to expect this kind of behavior, e.g:

 https://github.com/alexmingoia/koa-router#nested-routers (posts.allowedMethods() middleware will never be called, because no route matches the other HTTP methods)

I found the following issue: https://github.com/alexmingoia/koa-router/issues/182
which was fixed by: https://github.com/alexmingoia/koa-router/commit/e486a93da7739529d2807cbc3b1063f6dc1dbeef

The [comment](https://github.com/alexmingoia/koa-router/issues/182#issuecomment-179032019) made just some days ago by @rockie suggest that i'm not alone with this issue and that this problem also exists in the 5.x version of koa-router.

If I remove the [route check](https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L315) for my project, everything works as expected.

Take the following code as example, I want the API to respond with JSON for all errors `allowedMethods` throws on the `/api` route and to respond with HTML for everything else: 
```javascript
const Koa = require('koa')
const Router = require('koa-router')

const app = new Koa()
const router = new Router()

const apiRouter = new Router()

apiRouter.use((ctx, next) => {
  return next().catch(err => {
    ctx.status = 405
    ctx.body = { error: err }
  })
})

apiRouter.get('/entity', (ctx) => {
  ctx.body = { id: 0 }
})

router.use('/api', apiRouter.routes(), apiRouter.allowedMethods({
  throw: true
}))

router.get('/', (ctx) => {
  ctx.body = 'HTML'
})

app.use(router.allowedMethods())
app.use(router.routes())

app.listen(3000)
```
I expect `POST /api/entity` to return a JSON response:
```json
{
    "error": "Method Not Allowed"
}
```
but the middleware will be ignored completely and the top level `allowedMethods` will handle it and return HTML:
```html
Method Not Allowed
```
This example also works as expected if the [route check](https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L315) is removed.

----
I can think of many more use cases where middleware without matching routes are required. So is this behaviour really by design or am I doing something completely wrong?

**Comment by alexmingoia** [comment]
The whole point of route-specific middleware is to run middleware for a specific route. Otherwise there would be no functional different between `app.use()` and `router.use()`. If you want middleware to run regardless of any route matching you can mount it on the app via `app.use()`. 

Instead of nesting the `apiRouter` as route middleware for `router`, mount `apiRouter` separately using `app.use('/api', apiRouter.routes(), apiRouter.allowedMethods())`

**Comment by per2plex** [comment]
@aheckmann  Yeah, you're right. I gave it some more thought after I wrote this issue and it's actually more logical that way and the example above is actually the only use case where it would profit from working the other way, but there are some other clean solutions for that problem.

I'll close this issue. Thanks for the quick response tho, nice project you got here :+1:
