### ISSUE TITLE
Usage with graffiti

### ISSUE THREAD

**Issue by sibeliusseraphini** [alexmingoia/koa-router#245]
How can I use this package with https://github.com/RisingStack/graffiti ?

Is there an example?

I've tried this:

```javascript
router.use('/graphql', graffiti.koa({
    schema: Schema,
    graphiql: true,
  }));
```

But it didn't find the route

**Comment by alexmingoia** [comment]
Did you mount the router's middleware (`app.use(router.routes())`)?

**Comment by sibeliusseraphini** [comment]
yeah

**Comment by alexmingoia** [comment]
Hrm... the graffiti koa middleware signature looks fine. It will only work with koa-router v5.x because it uses generators. Also, it looks like it checks to make sure the `request.path === '/graphql'`, so if you're mounting it at any other URL like `'/api/graphql'` it won't work.

**Comment by sibeliusseraphini** [comment]
thanks for the explanation, I've fixed using koa-router to handle the requests - https://github.com/RisingStack/graffiti/issues/22#issuecomment-184228885
