### ISSUE TITLE
Code consistency in examples

### ISSUE THREAD

**Issue by felixsanz** [alexmingoia/koa-router#248]
Some examples use "new" and others not. Some use "router" and the ones with new, use "Router".

If its a constructor, use "new Router" everywhere, and if it's not, just don't.

I'ts confusing, which one is preferred?

**Comment by nightire** [comment]
According to https://github.com/alexmingoia/koa-router/blob/master/lib%2Frouter.js#L45-L47, both usage are fine, but I agree with you, the document should be consist.

**Comment by jbielick** [comment]
The docs should be up-to-date and consistent now. Constructors are capitalized.
