### ISSUE TITLE
this.cookies.set() cannot set cookie to chrome correctly

### ISSUE THREAD

**Issue by freestyle21** [alexmingoia/koa-router#253]
I came across a strange scene.

In the entry js file:

    app.use(function*(next) {
		this.cookies.set('test', 999999);
		return yield next;
	})

This is ok in both HTTP Response Header and Chrome Devtool Resources 's Cookies.

But...

When I put the `this.cookies.set` to Get Reponser

	app.get('/v1/test', function *(next) {
		this.cookies.set('test1', 66666);
		this.body = { code: 200, message: 'success'}
		return yield next;
	})

The HTTP Reponse Header is ok
	
	Set-Cookie: test1=66666; path=/; httponly

The Chrome Devtool Resources's Cookies display no cookie !

I have debugg this for long time, please help me ~

**Comment by alexmingoia** [comment]
`this.cookies` is from https://github.com/koajs/koa, not koa-router. Open an issue there.

**Comment by guihuxiansheng** [comment]
Error: Can't set headers after they are sent.
I got this error after using router.post,get or other methods.I think reason that those methods had send  the header.

**Comment by cdebotton** [comment]
I'm having an issue where if I set cookies or a session variable (using `koa-session`), the session is preserved using `router.get`, however when using `router.post`, the session and `ctx.cookies` are both unavailable.
