### ISSUE TITLE
Errors thrown in routes not passed to handlers

### ISSUE THREAD

**Issue by inca** [alexmingoia/koa-router#254]
Example (koa@2.0.0, koa-router@7.0.1):

```es6
router.use(async ctx => {
  throw new Error('hi');  // Internal server error, logged
});

router.get('/', async ctx => {
  throw new Error('hi');  // Not found, not logged
});
```

**Comment by inca** [comment]
Sorry, need more investigation (I might just not using it right). Will reopen if confirm that issue exists.

**Comment by inca** [comment]
Hey, this is how `koa-router` work: it doesn't execute any middleware if request doesn't match any routes. See #257 for more context.

I ended up creating [koa-router2](https://github.com/inca/koa-router2) module which works closer to my overall expectations. With it, error handling is regular Koa style:

```es6
app.use(async (ctx, next) => {
  try {
    await next();
  } catch (err) {
    // Do stuff, set status code, etc.
  }
});
```

**Comment by Niklv** [comment]
@inca thx a lot, i avoid it with `koa-mount`:
```javascript
app.use(mount(router.routes()));
app.use(
    mount(
        router.allowedMethods({
            throw: true,
            notImplemented: () => Boom.notImplemented(),
            methodNotAllowed: () => Boom.methodNotAllowed()
        })
    )
);
```

Strange behavior. It is a little bit frustration after using express router.
