### ISSUE TITLE
history api support for SPA?

### ISSUE THREAD

**Issue by jinmel** [alexmingoia/koa-router#255]
I am currently using [koa-connect-history-api-fallback](https://www.npmjs.com/package/koa-connect-history-api-fallback) to support automatic redirection to single page application router. But this kinda collides with koa-router because both of them acts on routing. 

could there be a specific option so that any unmatched url is automatically redirected to SPA?

**Comment by jbielick** [comment]
Could you just use a wildcard route to handle the unmatched urls?

```js
var koa = require('koa')
var app = new koa();
var router = require('koa-router')();
var assert = require('assert');
var request = require('supertest');

router.get('/resource', function* (next) {
  yield next;
});

router.get('/resource-two', function* (next) {
  yield next;
});

router.get('*', function* (next) {
  this.body = 'wildcard';
  yield next;
});

app
  .use(router.routes())
  .use(router.allowedMethods());

request(app.listen())
  .get('/some/unmatched/url')
  .expect(200)
  .end((err, res) => {
    assert(res.text == 'wildcard');
  });
```
