### ISSUE TITLE
internal route

### ISSUE THREAD

**Issue by MystK** [alexmingoia/koa-router#259]
I have a route, GET /getData/:format

The format can be XML or JSON. I would like users, when going to GET /getData, to be automatically internally routed to GET /getData/xml. Is this possible?

I am on koa-router@next

**Comment by jbielick** [comment]
is `/getData/xml` a separate route?

**Comment by MystK** [comment]
Hello, that is the same route, getData/:format

**Comment by jbielick** [comment]
like this?

```js
var koa = require('koa');
var app = new koa();
var router = require('koa-router')();

app.experimental = true;

router.get('/getData/:format?', function* (next) {
  var format = this.params.format || 'xml';
  this.body = `format is ${format}!`;
  yield next;
});

app
  .use(router.routes())
  .use(router.allowedMethods());

app.listen(8081);
```

`GET /getData` -> `format is xml!`
`GET /getData/xml` -> `format is xml!`
`GET /getData/json` -> `format is json!`

**Comment by MystK** [comment]
The problem for me was that /getData did not route to /getData/:format.

**Comment by jbielick** [comment]
did you include the question mark? `/getData/:format?`

**Comment by MystK** [comment]
Thanks. I didn't notice that until your pointed it out. I will try it out when I am back home, but I believe that the question mark was what I needed!

**Comment by jbielick** [comment]
The question mark should do it! Please reopen the issue if you have any further questions / problems.
