### ISSUE TITLE
redirect with data ?

### ISSUE THREAD

**Issue by smolleyes** [alexmingoia/koa-router#264]
hi

how can i do a redirect with json object like yield render('/my/page',{x:y}) ?

i have a form in /secure, then i submit (and try to not use ajax to keep html5 form validation) but in my route handler i render /secure/client/edit for exemple so my hrml is broken since path is wrong and it can t find css etc ...

thanks

**Comment by jbielick** [comment]
You'll have to add it to the url as a query string `?x=y&...` and you'll probably want to urlsafe base64 encode it if you're putting JSON in the url.
