### ISSUE TITLE
Layers do not support multiple parent layers

### ISSUE THREAD

**Issue by cb1kenobi** [alexmingoia/koa-router#266]
When you have nested layers and one of the middle layers has multiple paths that resolve the same next layer, then the next layer's path is prefixed with each middle layer's path over and over again.

#### Versions

* Koa.js master branch
* koa-router 7.0.1
* Node.js 5.10.1

#### Example

```javascript
'use strict';

const Koa = require('koa');
const app = new Koa();
const Router = require('koa-router');

const localRouter = new Router;
localRouter.get('/bar', ctx => {
	ctx.body = 'it works!';
});

const versionRouter = new Router;
versionRouter.use([
	'/0',
	'/0.x',
	'/0.1',
	'/0.1.x',
	'/0.1.0',
	'/latest'
], localRouter.routes());

const globalRouter = new Router;
globalRouter.use('/foo', versionRouter.routes());
app.use(globalRouter.routes());

app.listen(3000);
```

```
$ curl http://localhost:3000/foo/0/bar
Not found
$ curl http://localhost:3000/foo/0.x/bar
Not found
$ curl http://localhost:3000/foo/0.1/bar
Not found
$ curl http://localhost:3000/foo/0.1.x/bar
Not found
$ curl http://localhost:3000/foo/0.1.0/bar
Not found
$ curl http://localhost:3000/foo/latest/bar
Not found
```

#### Why do it this way?

This would be a no-brainer if koa-router supported regular expressions, but sadly it does not (#220).

`path-to-regexp` will allow some simple patterns such as `pathToRegexp('/foo/0(.x)?')`, but if you try to nested optional patterns, it will escape the question marks and thus won't work.

#### The root of the problem

Inside `router.js` in the `use()` function, for each middleware, it sets the `nestedLayer`'s prefix:

```javascript
if (path) nestedLayer.setPrefix(path);
```

In my case, the `nestedLayer` is the same and thus the path keeps getting prefixed.

Issue #247 is probably related to this.

#### Workaround

There is no workaround that wouldn't be considered a total hack. You'd have to define the route handler in a variable, then use a single router and define the full path and pass in the handler. For complex apps (such as mine), this is just not possible.

**Comment by jbielick** [comment]
is this similar to #244 ?

**Comment by cb1kenobi** [comment]
@jbielick Ah, yes. My bad. I didn't see that. Feel free to close this as a dupe.

**Comment by jbielick** [comment]
Love the amount of info here; wasn't suggesting this get closed, but wanted to make sure it was the same issue and not anther distinct.

**Comment by jbielick** [comment]
closing to track @ #244
