### ISSUE TITLE
How can I know which url wildcard matched?

### ISSUE THREAD

**Issue by ezesculli** [alexmingoia/koa-router#268]
I need to report to new relic which endpoint was executed to measure the performance. The problem is that now I'm reporting the URL of the request, but if the URL has an Id on it (parsed using parameters on the url), the URLs are reported as different endpoints to New Relic.

Is there a way to access from a middleware the matched url wildcard? 

Thanks, I appreciate if you can provide an example:

URL reported today:
/v1/users/571a68b84285620300e648e1#GET
/v1/users/666666666666666666666666#GET
/v1/users/999999999999999999999999#GET

How can I get from a middleware:
/v1/users/:usedId#GET

**Comment by jbielick** [comment]
Depending on the version you're using, `ctx._matchedRoute;` is available and is equal to `/v1/users/:usedId` in your example. This was added in 5.4. See [history.md](https://github.com/alexmingoia/koa-router/blob/5.x/history.md#540) for details.
