### ISSUE TITLE
Nested routes not working?

### ISSUE THREAD

**Issue by jmealo** [alexmingoia/koa-router#270]
```javascript
var router = new Router();
var comments = new Router();

comments.get('/', routes.comments.get);
comments.get('/:commentId', routes.comments.get);
comments.post('/', routes.comments.post);
comments.patch('/:commentId', routes.comments.patch);
comments.delete('/:commentId', routes.comments.delete);

router.use('/comments', comments.routes(), comments.allowedMethods());
router.use('/assign/learns/comments', comments.routes(), comments.allowedMethods());
router.use('/assign/conference_resources/comments', comments.routes(), comments.allowedMethods());
router.use('/assign/guiding_questions/comments', comments.routes(), comments.allowedMethods());
router.use('/assign/applies/comments', comments.routes(), comments.allowedMethods());|

// Auto-loader loads /assign/*entity route from fs (less specific then above routes)

app.use(router.routers());
app.use(router.allowedMethods());
```

All of the ``router.use()`` are getting a 404. I have routes defined using an auto-router but I did isolated tests and this never works as I expect it to.

I was hoping to do something with a wildcard where if the last part of the path is ``/comments`` or ``/comments/:commentId`` that I could have my comments middleware handle the nested request (bypassing the default root for nested resources). However, since I couldn't even get explicitly set routes to work and the above seems to require pattern matching or conditional routing, I gave up on that rather quickly.

Any ideas what to do here?  I thought routing was done by specificity. Here it's not even an issue of collision (I don't think...) it's an issue of it flat out not working? I did get the comments router to mount to my root path at one point using a nested router but I can't get it to work again.

Unless I'm making a mistake, this seems like undefined behavior, specificity and stacking (order of route definitions) "don't work" for this use case (or bug?).

I'm using koa: ^1.2.0 and koa-router: ^5.4.0.

I also tried using ``{prefix: "/comments"}`` with no luck.

Thanks,
Jeff

**Comment by gregaubert** [comment]
I have kind of the same problem... To me its seems like it's re-using the same router multiple time that doesn't seem to work (like "comments" in your exemple). Because it breaks as soon has I plug my router on more than one url...

**Comment by jbielick** [comment]
Thanks a ton for the detailed info and sample code, we'll track this issue at #244 and definitely refer to this to add more clarity.
