### ISSUE TITLE
"middleware must be a function"

### ISSUE THREAD

**Issue by uptownhr** [alexmingoia/koa-router#271]
```
var Koa = require('koa');
var app = new Koa()
var router = require('koa-router')();

router.get('/', function (ctx, next) {});
app.use('/', router.routes())
```

I'm using koa-router@7.01 with koa@2.  Any reason, I'm still receiving this error?

```
console.log( router.routes())

{ [Function: dispatch]
  router:
   Router{
   ....
```

**Comment by olsonpm** [comment]
I got that same error for a different reason - stumbled onto your issue.

See on koa's site:
http://koajs.com/#app-use-function-

You're probably confusing it with Express, which has routing built in
http://expressjs.com/en/4x/api.html#app.use

I'm sure you've solved your issue by now - but hopefully this helps future readers.

**Comment by uptownhr** [comment]
Yup, figured it out. Koa doesn't allow multiple middlewares and you cannot specify path like express on the `app.use` declaration. I fixed my problem by specifying the basepath on the router instead.

**Comment by harrylincoln** [comment]
@uptownhr are you able to shed some light on this issue?
https://stackoverflow.com/questions/60914997/middleware-must-be-a-function-for-koa-passport-testing-using-jest-typescript

For the life of me, can't figure it out. Missing something simple and koa-ish like you mentioned in your problem do you think?
