### ISSUE TITLE
Combining routers

### ISSUE THREAD

**Issue by zaynv** [alexmingoia/koa-router#272]
Right now, I have to do `app.use` with the `routes()` method on each of my routers. Example:

`app.use(rootRouter.routes())`
`app.use(userRouter.routes())`

Is there any way to combine the above into one router and then just be able to do something like

`app.use(combinedRouter.routes())` ?

Here is my current code:

**app.js**

``` javascript
const Koa = require('koa');
const rootRoutes = require('./routes/index')
const userRoutes = require('./routes/user')

const app = new Koa()

app.use(rootRouter.routes())
app.use(userRouter.routes())

app.listen(3000)

export default app
```

**routes/index.js**

``` javascript
import Router from 'koa-router'
const router = new Router()

router.get('/', async ctx => {
  await ctx.render('index')
})

router.get('/about', async ctx => {
  await ctx.render('about')
})

export default router
```

**routes/user.js**

``` javascript
import Router from 'koa-router'
const router = new Router({ prefix: '/user' })

router.get('/:name', async ctx => {
  const user = ctx.params.name
  await ctx.render('user', { user })
})

export default router
```

**Comment by Krisa** [comment]
Looking for doing the same. There are actually double more app.use, because there is `routes` but also `allowedMethods` for each Router.

This makes "hot-reloading" like described [here](https://github.com/glenjamin/ultimate-hot-reloading-example/issues/17) much more challenging.

**Comment by gingerich** [comment]
I think [koa-compose](https://github.com/koajs/compose) could do the trick.

`app.use(compose([router1.routes(), router2.routes()]))`

That's what koa is doing under the hood anyways

**Comment by saadq** [comment]
^ gingerich is right. 

For convenience, I created a [separate module](https://github.com/saadq/koa-combine-routers) which is just a wrapper around koa-compose to combine instances of koa-router. Instead of doing something like this:

```javascript
import compose from 'koa-compose'
import router1 from './router1'
import router2 from './router2'
import router3 from './router3'

const router = compose([
  router1.routes(),
  router1.allowedMethods(),
  router2.routes(),
  router2.allowedMethods(),
  router3.routes(),
  router3.allowedMethods()
])

export default router
```

You'll be able to do this:

```javascript
import combineRouters from 'koa-combine-routers'
import router1 from './router1'
import router2 from './router2'
import router3 from './router3'

const router = combineRouters([
  router1,
  router2,
  router3
])

export default router
```

Avoids a bit of repetition.

**Comment by zaynv** [comment]
Thanks! I would like for there to be some way to do this in `koa-router` itself, but for now I'll go with using your package.

**Comment by dmtrs** [comment]
I am not sure if this is the correct place or what I am trying to achieve is aligned with the above
```js
const Koa = require('koa');
const app = new Koa();

const Router = require('koa-router');

const foo = new Router({ prefix: '/foo' });
foo.get('/', ctx => ctx.body = '/foo' );

const bar = new Router({ prefix: '/bar' });
bar.get('/', ctx => ctx.body = '/bar' );

const dup = new Router({ prefix: '/dup' });
dup.get('/', ctx => ctx.body = '/dup' );

bar.use('/', dup.routes(), dup.allowedMethods());
foo.use('/', bar.routes(), bar.allowedMethods()); // explGET /foo/bar, GET /foo/bar/dup
foo.use('/', dup.routes(), dup.allowedMethods()); // GET /foo/dup

app.use(foo.routes()).use(foo.allowedMethods());

app.listen(3000);
```
This is my code but I get following results in matters of status codes for the above urls
```
$ curl localhost:3000/foo
/foo
$ curl localhost:3000/foo/bar
Not Found
$ curl localhost:3000/foo/dup
Not Found
$ curl localhost:3000/foo/bar/dup
Not Found
```
What I want is to have the same routes / methods under /foo/dup and /foo/bar/dup path
