### ISSUE TITLE
Appears to be setting multiple Allow headers instead of one comma separated header.

### ISSUE THREAD

**Issue by billmalarky** [alexmingoia/koa-router#273]
When an options request is made to an app using koa-router, multiple "Allow" headers are set instead of one header with a comma separated value.

For example, I've got a route that currently only supports GET requests. When I ping it with an OPTIONS request, it should attach a header like:

Allow: HEAD, GET

but instead if I inspect the response headers with chrome dev tools, I get

Allow:HEAD
Allow:GET

You can quickly confirm this by pointing the following jsfiddle at your testing koa-router enabled app and firing a request.

http://jsfiddle.net/QZ3ff/706/

Just update "http://example.com/koa-router-app" to your test app and put any arbitrary data in the message box and fire the request.

**Comment by joebartels** [comment]
seeing the same thing ^

**Comment by jbielick** [comment]
fixed in #376
