### ISSUE TITLE
router bug

### ISSUE THREAD

**Issue by einsqing** [alexmingoia/koa-router#274]
路由规则
*/admin/order*/page/:page

```
{ '0': '/api/admin/order/status//pay_status/1/page/1',
  '1': '/status//pay_status/1'}
```

路由规则
/admin/order*/page/:page

`{ '0': '/api/admin/order/status//pay_status/1/page/1'}
`

**Comment by lumberj** [comment]
Anybody?

**Comment by lumberj** [comment]
Looks like this happens when nesting routers without specifying the mount path:

`router1.use(router2)`
vs.
`router1.use('/', router2)`

**Comment by einsqing** [comment]
I almost forget this issue, thanks
