### ISSUE TITLE
How to prevent the context response immediately?

### ISSUE THREAD

**Issue by Manjiz** [alexmingoia/koa-router#276]
``` javascript
router.get('/api/test', function *(){
  setTimeout(() => {
      this.body = 'wwww';
  }, 1000);
});
```

I got Not Found! Why? It's distinct from Express.

**Comment by Manjiz** [comment]
For hack, I must wrapped up it with a Promise.

**Comment by i5ting** [comment]
https://github.com/koajs/koa/issues/734

**Comment by jbielick** [comment]
> For hack, I must wrapped up it with a Promise.

That's not a hack; that's how koa works. Your generator function is being called, and you're not yielding to anything. Your timeout happens out of band and you haven't instructed your generator function to yield control to another object (Promise, another generator, etc).
