### ISSUE TITLE
How to make koa-router and koa-views work together?

### ISSUE THREAD

**Issue by tangdaohai** [alexmingoia/koa-router#277]
Hi everyone.
    can't use koa-views? my code :

    let Koa = require("koa"),
        app = new Koa(),
        co = require("co"),
        views = require("koa-views"),
        router = require("koa-router")();
    // my ejs 
    app.use(views(__dirname + "/public",{ extension: 'ejs' }));
    
    app.use(co.wrap(function *(ctx, next) {
        yield ctx.render("index", ctx.query);
    }));

The above code works fine. But when I use koa-router that not work, I got Not Found. Why...? 

     let Koa = require("koa"),
        app = new Koa(),
        co = require("co"),
        views = require("koa-views"),
        router = require("koa-router")();
    //my ejs 
    app.use(views(__dirname + "/public",{ extension: 'ejs' }));
    router.get("/index", function (ctx){
         console.log(ctx.ptah); // ==> /index
         ctx.render("index", {a : 1}); 
     });

    //app.use(co.wrap(function *(ctx, next) {
    //    yield ctx.render("index", ctx.query);
    //}));

my package.json :

    {
          "name": "test",
          "version": "1.0.0",
          "description": "",
          "dependencies": {},
          "devDependencies": {
            "co": "^4.6.0",
            "ejs": "^2.4.1",
            "gulp": "^3.9.1",
            "gulp-nodemon": "^2.0.7",
            "koa": "^2.0.0",
            "koa-bodyparser": "^3.1.0",
            "koa-convert": "^1.2.0",
            "koa-logger": "^1.3.0",
            "koa-router": "^7.0.1",
            "koa-views": "^5.0.1"
          },
          "scripts": {}
        }
What should I do, Can you help me. 
Thanks

**Comment by tangdaohai** [comment]
I solved the problem, so simple... 
    
     router.get("/index", function (ctx){
         console.log(ctx.ptah); // ==> /index
         return ctx.render("index", {a : 1});   // add return...  that working fine 😄
     });

**Comment by i5ting** [comment]
@tangdaohai 确实是需要return的，关掉这个问题吧

**Comment by tangdaohai** [comment]
@i5ting 桑大神 😄
