### ISSUE TITLE
Can anyone get koa-websocket to work with koa-router@7.0.1?

### ISSUE THREAD

**Issue by chovy** [alexmingoia/koa-router#281]
koa-websocket works fine with koa-router@5.x but not 7.

https://github.com/kudos/koa-websocket/issues/14

If anyone can point me in the right direction of how to fix this library I can create a PR.

I think it has to do with this line but I'm not sure how to fix it for 7.x

https://github.com/kudos/koa-websocket/blob/master/index.js#L27

**Comment by chovy** [comment]
bump

**Comment by cymen** [comment]
I ran into this too. I haven't had a chance to dig into it yet but switching to `koa-route` for the websocket route made it work (although not sure if that is actually a solution for my usage, just did it to debug which part wasn't working).

**Comment by chovy** [comment]
Can you paste an example of how you worked around this?

**Comment by cymen** [comment]
@chovy I adapted this example from the `koa-websocket` README:

```javascript
const koa = require('koa'),
  route = require('koa-route'),
  websockify = require('koa-websocket');
 
const app = websockify(koa());
 
// Note it's app.ws.use and not app.use 
app.ws.use(route.all('/test/:id', function* (next) {
  // `this` is the regular koa context created from the `ws` onConnection `socket.upgradeReq` object. 
  // the websocket is added to the context on `this.websocket`. 
  this.websocket.send('Hello World');
  this.websocket.on('message', function(message) {
    // do something with the message from client 
    console.log(message);
  });
  // yielding `next` will pass the context (this) on to the next ws middleware 
  yield next;
}));
 
app.listen(3000);
```

That uses `koa-route` instead of `koa-router`. That made websockets work from my local HTTP server.

So it was just pin-pointing that `koa-router` appears to be the breaker. I'm just getting started with websockets and Koa so I might have it wrong but I was hoping that if `koa-router` worked, I'd be able to get the current logged in user and such (ie in my other normal routes, `ctx.req.user`). Maybe I can get `koa-route` to hook into that too but wasn't sure.

**Comment by chovy** [comment]
oh, it uses generators not async/await? that sucks.

**Comment by jbielick** [comment]
Is `koa-websocket` written for koa 2? Koa 2 middleware signatures have changed and so has `koa-compose`. Is `koa-websocket` is compatible with koa2 in general?

**Comment by chovy** [comment]
@jbielick it was originally for koa@1.x but i don't think support for 2.x would be that difficult. I linked to the line I think is the problem.

**Comment by cymen** [comment]
I opened a PR over at koa-websocket for a `next` as @jbielick points out it definitely looks like signature change.

https://github.com/kudos/koa-websocket/pull/18

**Comment by jbielick** [comment]
@cymen nice! Great stuff. Closing this comment as it can be tracked at https://github.com/kudos/koa-websocket/issues/14 or https://github.com/kudos/koa-websocket/issues/18
