### ISSUE TITLE
Getting matched route with koa 2

### ISSUE THREAD

**Issue by jsfr** [alexmingoia/koa-router#290]
b2a89eeeea0cbf942d70007ffc7cdf385a31b9e5 exposed the matched route for the 5.x branch. However on master this commit does not exists. Is there a way to get the matched route when using koa 2 and the respective version of koa-router?

**Comment by zaynv** [comment]
Is there a difference between `_matchedRoute` and `this.url`?

**Koa 1**

```javascript
router.get('/test', function * (next) {
  console.log(this._matchedRoute) // Output: /test
  console.log(this.url) // Output: /test
})
```

**Koa 2**

```javascript
router.get('/test', async (ctx, next) => {
  console.log(ctx.url) // Output: /test
})
```

**Comment by jsfr** [comment]
`_matchedRoute` will give you the route that is matched so .e.g `/test/:id` where as `this.url` will give you the actual url so e.g. `/test/123` instead afaik. I need the matched route and not the url for logging performance using tools such as opbeat.

**Comment by jbielick** [comment]
koa-router 5.4 changes (`_matchedRoute`) have now been backported in the [`master` branch (v7.1.0)](https://github.com/alexmingoia/koa-router/commit/865c27d68818bbeaa4026e460ef933d2d33682df).

@jsfr you should be good to go! Reopen if there are issues
