### ISSUE TITLE
Is there a way to use same url with different controller?

### ISSUE THREAD

**Issue by bingdian** [alexmingoia/koa-router#291]
function *MobileIndexController() {
        this.body = 'Mobile Device';
    }

    function *DesktopIndexController() {
        this.body = 'Desktop Device';
    }

    function *handlerRoutes() {
        if ( desktop ) {
            // IndexController => DesktopIndexController
        } else {
            // IndexController => MobileIndexController
        }
    }

    app.get('/', handlerRoutes,  IndexController);

**Comment by jbielick** [comment]
Sure. Something like the following should work:

```js
function *MobileIndexController() {
    this.body = 'Mobile Device';
}

function *DesktopIndexController() {
    this.body = 'Desktop Device';
}

function *handlerRoutes() {
    if (desktop) {
      yield DesktopIndexController
    } else {
      yield MobileIndexController
    }
}

app.get('/', handlerRoutes);
```
