### ISSUE TITLE
What's means to use the normal function as a middleware ?

### ISSUE THREAD

**Issue by KID-WuMeng** [alexmingoia/koa-router#294]
I have a code by CoffeeScript like:

```js
router.post '*', (next) ->
  console.log 'first'
  yield next

router.post '/abc', ->
  console.log 'second'
```

If there are no 'yield' keywords, CoffeeScript will think it is a normal function. Sometimes I forget the yield next when the middleware is a return-point middleware.

The example will print 'second', 'first'. Of course, I hope to print 'first', 'second'...

So I have a question that If i use the normal function in middleware, what will happen? why call the normal function early than the generator function?

**Comment by helloyou2012** [comment]
@KID-WuMeng  https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L326-L330

```
1. matched /abc
2. run next = normalFunction(next)     // log 'second' & next == undefined

3. matched *
4. run next = generatorFunction(next)  // next == Iterator Object

5. run yield *next                     // log 'first'
```

**Comment by KID-WuMeng** [comment]
@helloyou2012 I see and thanks ~
