### ISSUE TITLE
async/await next is not being passed and is undefined in koa2 

### ISSUE THREAD

**Issue by sschenk** [alexmingoia/koa-router#297]
I'm trying to refactor my code to async await which looks great, but trying to use next doesn't work. I keep getting next is not defined and I can't sem to find any info. what am I missing?
```
router.post('/api/userupdate',
  async (ctx, next) => {
    try {
      await next() // All my nexts like this one here are undefined 
    } catch (err) {
      ctx.body = { message: err.message }
      ctx.status = err.status || 500
    }
  },
  async (ctx, next) => {
   //just checking 
   console.log('here')
    const token = ctx.request.headers.authorization.split(' ')[1]
    const uid = await jwt.verify(token, config.database.jwtSecret)
    console.log(uid)
  })
```

**Comment by sschenk** [comment]
So basically if I try to do the following  gives me an undefined this and next and an empty object on ctx:

```
router.post('/api/userupdate', async (ctx, next) => {
  console.log(this)
  }
) 
``` 

Am I suppose to do ctx = this somewhere earlier?

**Comment by KingWu** [comment]
i also get undefined 'this'. But why?

**Comment by jbielick** [comment]
could you post your `package.json`? What version of `koa-router` are you using (specifically)?

**Comment by jbielick** [comment]
This test case (which resembles yours), passes if run with [v7.0.0-nightly20160930f5d997c476](https://nodejs.org/download/nightly/v7.0.0-nightly20160930f5d997c476/) and the `--harmony` flag.

```
  "dependencies": {
    "koa": "2.0.0-alpha.7",
    "koa-router": "7.0.1",
    "supertest": "2.0.0"
  },
```

```js
const koa = require('koa');
const app = new koa();
const router = require('koa-router')();
const assert = require('assert');
const request = require('supertest');

app.experimental = true;

router.get('/', async (ctx, next) => {
  await next();
  ctx.body += await returnLater('\nruns second');
}, async (ctx, next) => {
  ctx.body = await returnLater('runs first');
});

app.use(router.routes());

function returnLater(string) {
  return new Promise(function(resolve, reject) {
    setTimeout(function() {
      resolve(string);
    }, 200);
  });
}

request(app.listen())
  .get('/')
  .expect(200)
  .end((err, res) => {
    assert(res.text === 'runs first\nruns second');
    process.exit(0);
  });
```

Maybe there's something wrong with your transpiling? Are you using the correct version of koa? Check the dependency list above and make sure you're on koa-2 (alpha)

**Comment by KingWu** [comment]
For me, my package.json is

> {
  "dependencies": {
    "aws-sdk": "~2.5.1",
    "bluebird": "^3.4.6",
    "cheerio": "~0.19.0",
    "continuation-local-storage": "^3.1.4",
    "cookies": "^0.6.1",
    "email-templates": "^2.4.1",
    "exceljs": "~0.2.3",
    "kcors": "~1.3.0",
    "kerberos": "~0.0.17",
    "koa": "~2.0.0",
    "koa-bodyparser": "~3.2.0",
    "koa-compress": "~2.0.0",
    "koa-logger": "~2.0.0",
    "koa-router": "~7.0.0",
    "koa-send": "~3.2.0",
    "koa-static": "~3.0.0",
    "koa-validate": "^1.0.7",
    "lodash": "~4.16.2",
    "moment": "~2.10.6",
    "mysql": "~2.11.1",
    "node-uuid": "^1.4.7",
    "nodemailer": "^2.6.4",
    "nodemailer-direct-transport": "^3.3.2",
    "nodemailer-smtp-transport": "^2.7.2",
    "parse5": "~2.0.1",
    "request": "~2.67.0",
    "request-promise": "~1.0.2",
    "sequelize": "~3.24.3",
    "sequelize-auto-ts": "~1.0.11",
    "swagger-jsdoc": "~1.7.0",
    "winston": "~2.1.1"
  },
  "devDependencies": {
    "supertest": "^2.0.0",
    "chai": "~3.5.0"
  }
}

**Comment by jbielick** [comment]
Please check the other libraries that you are using to ensure that they are compatible with koa2. I have setup a test case with the same versions of `koa-router`, `koa` as your package.json and everything works as intended. 

```js
  "dependencies": {
    "koa": "~2.0.0",
    "koa-router": "~7.0.0",
    "supertest": "2.0.0"
  },
```

```js
const koa = require('koa');
const app = new koa();
const router = require('koa-router')();
const assert = require('assert');
const request = require('supertest');

app.experimental = true;

router.get('/', (ctx, next) => {
  return next();
}, (ctx, next) => {
  ctx.body = 'hi';
});

app.use(router.routes());

function returnLater(string) {
  return new Promise(function(resolve, reject) {
    setTimeout(function() {
      resolve(string);
    }, 200);
  });
}

request(app.listen())
  .get('/')
  .expect(200)
  .end((err, res) => {
    assert(res.text === 'hi');
    process.exit(0);
  });
```

Please reopen this issue if you can produce a test case that fails using koa2 and koa-router 7. The other koa libraries in your app _might_ be the culprit.
