### ISSUE TITLE
Cherry picking routes with layers

### ISSUE THREAD

**Issue by wlingke** [alexmingoia/koa-router#298]
Is it possible to cherrypick and transplant a route from one router to another? See example below. I understand that I can get a Layer object from `router.route` but not sure what to do with this? Using `router.use()` doesn't seem to work.

```
    //router1.js:
    const router = new Router();
    router.post('pickme', '/', someHandler);
    export default router;
    
    //router2.js
    import router1 from './router1.js'
    const router = new Router();
    const cherryPickedRoute = router1.route('pickme') //What to do with this??
    export default router
```

**Comment by jbielick** [comment]
`route()` [returns a `Layer`](https://github.com/alexmingoia/koa-router#routerroutename--layer--false), which cannot be mounted / used as middleware or a handler. So I don't think this is possible. You could just re-use the function / path / handler in two routers?
