### ISSUE TITLE
How can i know whether matched a path ?

### ISSUE THREAD

**Issue by kid-wumeng** [alexmingoia/koa-router#299]
For example, I have a route:

``` js
router.post('/user/books', function*(){...})
```

I hope know if one request matched the path. In fact, I handling the 404 response now. Some api can respond some data, and some none. If an api don't respond some data, in other words, the this.body is undefined, koa-router will respond a 404 status. In the case, should respond a 200 status.

The router.route() method's param is name. Is there a way to know route by path ?

**Comment by mmukarram** [comment]
There is an undocumented attribute on the context ```_matchedRoute``` that you can use to verify the path that was matched. Keep in mind that if your router is mounted separately on the application, i.e. ```mount('/mount', router.routes())```, then you will not get the full path, just your router prefix onward.

**Comment by watson** [comment]
@mmukarram I'm not sure what you mean by mount?

I've literally tried all ways I could come up with for mounting and it all gives the full path. I am using `koa-router@5` - is the mount stuff you're talking about related to v7?

This is an example app showing all the ways to define routes that I could think off:

```js
var koa = require('koa')
var Router = require('koa-router')

var app = koa()
var root = new Router()
var sub = new Router()
var prefix = new Router({prefix: '/prefix'})
var lazyPrefix = new Router()
lazyPrefix.prefix('/lazy/:foo')

sub.get('/:id', route)
prefix.get('/:id', route)
lazyPrefix.get('/:id', route)

root
  .get('/', route)
  .get('/normal/:id', route)
  .get('foo', '/name/:id', route)
  .use('/sub', sub.routes(), sub.allowedMethods())
  .use('/prefix', prefix.routes(), prefix.allowedMethods())
  .use('/lazy', lazyPrefix.routes(), lazyPrefix.allowedMethods())

function *route (next) {
  this.body = this._matchedRoute
}

app
  .use(root.routes())
  .use(root.allowedMethods())

app.listen(3000)
```
