### ISSUE TITLE
Update docs for mounting router at base URL

### ISSUE THREAD

**Issue by justinbelcher** [alexmingoia/koa-router#30]
Is it possible to have a base URL for all resources like `api/v1`? Or should that be handled elsewhere via proxy or mount?

**Comment by paramsinghvc** [comment]
app.use only takes one argument as middleware.

**Comment by tknappra** [comment]
The prefix option.
https://github.com/koajs/router/blob/HEAD/API.md#router-prefixes

I'll also post it here as well for convenience.
```js
const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router = new Router({ prefix: '/api' });

router.get('/', (ctx, next) => {
   // ...
});

app
  .use(router.routes())
  .use(router.allowedMethods());
```
