### ISSUE TITLE
publish 7.1 to npm

### ISSUE THREAD

**Issue by stephenmathieson** [alexmingoia/koa-router#304]
I also need `._matchedRoute`, but v7.1.0 isn't in npm:

```
npm ERR! No compatible version found: koa-router@7.1
npm ERR! Valid install targets:
npm ERR! 7.0.1, 7.0.0, 6.2.0, 6.1.0, 6.0.1, 6.0.0, 5.4.0, 5.3.0, 5.2.3, 5.2.2, 5.2.1, 5.2.0, 5.1.2, 5.1.1, 5.1.0, 5.0.1, 5.0.0, 4.3.2, 4.3.1, 4.3.0, 4.2.0, 4.1.0, 4.0.1, 4.0.0, 3.8.0, 3.7.0, 3.6.0, 3.5.0, 3.4.0, 3.3.1, 3.3.0, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 3.0.0, 2.4.4, 2.4.3, 2.4.1, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.0, 2.1.0, 2.0.1, 2.0.0, 1.6.1, 1.6.0, 1.5.5, 1.5.4, 1.5.3, 1.4.3, 1.3.3, 1.2.3, 1.2.2, 1.1.2, 1.1.1, 1.0.1, 1.0.0
```

**Comment by tiant167** [comment]
+1

**Comment by jsfr** [comment]
Is there an ETA for when this will happen? I don't really understand the hold-up?

**Comment by jbielick** [comment]
@jsfr permissions to contribute on GitHub do not equate to permissions to publish the package ok npm. Code had been merged to the repo on GitHub for 7.0, but none of the contributors have permissions to publish that version to NPM. 

Feel free to [install the package from the github repo directly](http://stackoverflow.com/a/23348036). This is a pretty common thing.

**Comment by stephenmathieson** [comment]
@alexmingoia can you please give @jbielick npm push permissions for this repo? I'm not comfortable relying on GitHub for `npm install`s.

**Comment by nfantone** [comment]
@alexmingoia Any chance this could be worked out any time soon?

**Comment by ianstormtaylor** [comment]
Any word on this @alexmingoia? I'm also looking to use `_matchedRoute` with Koa 2. Thanks!

**Comment by chovy** [comment]
isn't it just `npm install koa-router@next`?

**Comment by stephenmathieson** [comment]
@chovy to get v7.0.1, yes, that'll work. v7.1.0 isn't published to npm tho

**Comment by nfantone** [comment]
Ping @alexmingoia

**Comment by nfantone** [comment]
Ping @alexmingoia

**Comment by alexmingoia** [comment]
It's published now. I'll add publishing permissions for some of the contributors.

**Comment by stephenmathieson** [comment]
Thanks dude!

**Comment by ianstormtaylor** [comment]
Looks like `7.1.0` isn't tagged with `next`, so `koa@next -> 7.0.1`
