### ISSUE TITLE
How does allowedMethods work?

### ISSUE THREAD

**Issue by felixsanz** [alexmingoia/koa-router#305]
I have a file routes.js with this content:

``` javascript
import Router from 'koa-router'

function routes(components) {
  const router = new Router()
  router.get('/home', components.home)
  return router
}

export default routes
```

And i call it by `const router = routes(components)`.

But when i do this:

``` javascript
server.use(router.routes())
server.use(router.allowedMethods())
```

Seems like allowedMethods is not working because even if i use POST or PATCH, i'm getting the response anyway. Why i'm not getting `405 Method Not Allowed` or `501 Not Implemented` ?

Thanks

**Comment by s1mpleinfo** [comment]
const router = require('koa-router')()

router.get('/health', async (ctx) => {
  ctx.body = {
    status: 'UP'
  }
})

**Comment by s1mpleinfo** [comment]
```
like this
```
