### ISSUE TITLE
Not able to use koa-router for passport login

### ISSUE THREAD

**Issue by ersuryapurohit** [alexmingoia/koa-router#310]
Tried using the following:

```
router.post('/login', async(ctx, next) => {
  await passport.authenticate('local', {
    successRedirect: '/about',
    failureRedirect: '/'
  })
})
```

and

```
router.post('/login', passport.authenticate("local", {
    successRedirect: '/about',
    failureRedirect: '/'}), async(ctx, next) => {
        await passport.authenticate('local', {
            successRedirect: '/about',
            failureRedirect: '/'
       })
})
```

and

```
router.post('/login', passport.authenticate('local', {
    successRedirect: '/about',
    failureRedirect: '/'
})
```

but neither worked. Where should I use to get passport authentication working with KOA2?

[URL to the stackoverflow question](http://stackoverflow.com/questions/40459590/passport-authenticate-is-not-working-at-all)

**Comment by jbielick** [comment]
You're going to have to reduce this to a simple test case that exhibits the bug you're describing or ask the question in `koa-passport`. You have too much middleware and context for anyone to debug this issue.
