### ISSUE TITLE
Maybe router prefix should can be regexp?

### ISSUE THREAD

**Issue by arusakov** [alexmingoia/koa-router#312]
I wanna versioning API via url prefix, something like this:
```
/api/path
/api/v1/path
/api/v2/path
```
Does `koa-router` has design limitations about it? If not, I can figure it out and make PR.

**Comment by jbielick** [comment]
`koa-router` [supports prefixes](https://github.com/alexmingoia/koa-router#router-prefixes) out of the box. I don't think regex prefixes would add a lot of value. Prefixes are typically explicit (as versions of an api, for example). What you're describing is possible with koa-router.
