### ISSUE TITLE
Koa Router Factory

### ISSUE THREAD

**Issue by YannickDa** [alexmingoia/koa-router#313]
Hello,

I've developed a new module that I've called koa-router-factory (https://github.com/YannickDa/koa-router-factory) to use koa-router with a config file. It's more easelier to define routes througth config file.

I don't know if you are interested to integrate the factory function to koa-router directly ? If so, I can create a merge request to integrate this feature, else, no problems ;)

Thanks,
Yannick

**Comment by jbielick** [comment]
Probably not, but I'm sure many will appreciate your module. Perhaps it's best used alongside koa-router as a peerDependency? It's nice to be able to install only what one needs and install an additional module for extra functionality like this. Best of luck!
