### ISSUE TITLE
Some changes not apply to branch 5.x

### ISSUE THREAD

**Issue by zbinlin** [alexmingoia/koa-router#318]
I see that some features only apply to the master branch, but not applied to the 5.x branch. but the features logged in the history.md.

For example, In the [history.md](https://github.com/alexmingoia/koa-router/blob/5.x/history.md), the `Register multiple routes with array of paths` feature is ship on v5.3.0, and I through the issue #203 that I know the commit of this feature is 
https://github.com/alexmingoia/koa-router/commit/dde14ae71676a96d612d60ef3b9948f035e5cb9d, but I did not found the commit in 5.x branch.

ref:
https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L502
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L495

**Comment by jbielick** [comment]
Yeah, see #304. Nobody has npm publishing capabilities right now. You can [install the branch you want from github](http://stackoverflow.com/questions/23338393/npm-install-not-installing-latest-version-on-github/23348036#23348036). Sorry!
