### ISSUE TITLE
ctx.render is not a function

### ISSUE THREAD

**Issue by showzyl** [alexmingoia/koa-router#319]
Node version: v7.2.0

app.js

const router = require('koa-router')();
const index = require('./router/index');
router.use('/', index.routes(), index.allowedMethods());

./router/index.js

const router = require('koa-router')();
router.get('/', async function (ctx, next) {
	ctx.state = {
		title: 'koa2 title'
	};
	await ctx.render('index', {
		user: 'John'
	});
});

module.exports = router;

(node:2617) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: ctx.render is not a function
(node:2617) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by jbielick** [comment]
Are you using a library that provides a "render" method? Your example doesn't show one.

**Comment by showzyl** [comment]
solve this proble.
https://github.com/showzyl/koa2-boilerplate
