### ISSUE TITLE
Inconsistency in the api/Readme

### ISSUE THREAD

**Issue by johnzielke** [alexmingoia/koa-router#320]
In the readme, the router method for DELETE is, opposed to all other methods, not called delete(...), but del(...). Is there any reason for that, except it being a tad shorter? Otherwise, I would suggest to have an alias for that method (in order not to break the api). At least we should not refer to the method in the Docs as "delete" to prevent confusion. For example:
![image](https://cloud.githubusercontent.com/assets/20091488/21069367/6fe189e6-be79-11e6-8d4c-043b0990884c.png)

**Comment by jbielick** [comment]
This is pretty common practice as `delete` [is a reserved word in JavaScript](http://stackoverflow.com/questions/18793529/is-it-safe-to-declare-a-delete-method-in-javascript). Not all interpreters treat it the same; for sanity's sake most authors avoid using it. 

Feel free to submit a pr + tests.

**Comment by jbielick** [comment]
This is already aliased https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L192
