### ISSUE TITLE
Please complete the documents...

### ISSUE THREAD

**Issue by blade254353074** [alexmingoia/koa-router#332]
I saw `Router.prototype` has a lot of methods but only a few of those are written into the document.

```js
[ 'acl', 'bind', 'checkout', 'connect', 'copy', 'delete', 'get', 'head', 'link', 'lock', 'm-search', 'merge', 'mkactivity', 'mkcalendar', 'mkcol', 'move', 'notify', 'options', 'patch', 'post', 'propfind', 'proppatch', 'purge', 'put', 'rebind', 'report', 'search', 'subscribe', 'trace', 'unbind', 'unlink', 'unlock', 'unsubscribe', 'del', 'use', 'prefix', 'middleware', 'routes', 'allowedMethods', 'all', 'redirect', 'register', 'route', 'url', 'match', 'param' ]
```

**Comment by jbielick** [comment]
Which "public" methods do you think are missing from the docs? You may find that while you're here on github that you can read the source code and derive a description for yourself. You could then add some documentation and make a pull request to contribute to the project.

**Comment by blade254353074** [comment]
Thank you~ I got it.
I would like to add some docs if I'm free.
