### ISSUE TITLE
Update the 'next' tag to 7.1.0

### ISSUE THREAD

**Issue by natesilva** [alexmingoia/koa-router#333]
`npm install koa-router@next` currently gets version 7.0.1. The latest version on the master branch is 7.1.0.

**Comment by ilkkao** [comment]
2.x branch should the default branch now. Koa 2.0.1 got released a day ago.

**Comment by BruceHem** [comment]
do i still need to put @next?

**Comment by rally25rs** [comment]
Also remember to correct the 'installation' docs whenever this this change is made
https://github.com/alexmingoia/koa-router/tree/master/#installation

**Comment by osenvosem** [comment]
Koa 2 has already been released but the router is still under the `next` tag:

```
yarn info koa-router dist-tags                                               /Volumes/Data/development/dev/k
yarn info v0.21.3
{ latest: '5.4.0',
  next: '7.0.1' }
```
