### ISSUE TITLE
Update default installed version

### ISSUE THREAD

**Issue by pensierinmusica** [alexmingoia/koa-router#336]
Hi,

Koa 2 has been released by some time now, could you please update the default installed `koa-router` version according to this [package docs](https://github.com/alexmingoia/koa-router/tree/master/#installation):

> When koa 2 is released, 7.x will be tagged with latest and installed by default by NPM.

(Relates to #333)

**Comment by mrpatiwi** [comment]
I hope to see this resolved soon 😄

**Comment by pensierinmusica** [comment]
@alexmingoia or @tj do you want me to send a pr?

**Comment by jbielick** [comment]
@alexmingoia who has publishing permissions?

**Comment by alexmingoia** [comment]
@jbielick Sorry I thought I had added you but was mistaken. You should be able to publish on npm now. I went ahead and published 5.4.1 and 7.1.1

**Comment by jbielick** [comment]
Thanks, @alexmingoia !

**Comment by pensierinmusica** [comment]
@alexmingoia and @jbielick so shall we close this issue now? Cheers

**Comment by mrpatiwi** [comment]
But Koa v2 was released and `koa-router@latest` still targets Koa v1. This doesn't resolve the original issue 😢

**Comment by jbielick** [comment]
```
> npm dist-tag add koa-router@v7.1.1 latest
+latest: koa-router@v7.1.1
> npm dist-tag ls
latest: 7.1.1
next: 7.1.1
```

should be good now. Do we need to `rm` the `@next` tag?

**Comment by mrpatiwi** [comment]
It is also needed to set `master` as the default branch in this repository

**Comment by jbielick** [comment]
That I cannot do

**Comment by jbielick** [comment]
Latest should be publishing correctly, for the default branch, we'll can track on #352
