### ISSUE TITLE
hope koa-router also use `router.delete`

### ISSUE THREAD

**Issue by tomoat** [alexmingoia/koa-router#338]
delete is a reserved keyword in JavaScript. However, as of ECMAScript 6, delete and other reserved keywords can legally be used as property names.

express5 use `app.delete` not support `app.del`

hope koa-router also use `router.delete`

**Comment by a-rodin** [comment]
But `koa-router` already uses `router.delete` and `router.del` is just an alias.

**Comment by tomoat** [comment]
ohohoh.
