### ISSUE TITLE
Get current route from the handler

### ISSUE THREAD

**Issue by a-rodin** [alexmingoia/koa-router#341]
I have this code

```js
router.get('/user/:id', ctx => {
    ctx.body = `hi, ${ctx.url}`
})
```

As expected it returns `/user/name` for cases when I try to do request to `/user/name` path.

However I want to also get `/user/:id` string (to pass it to an ACL middleware). In Express 4 it is possible with [req.route](https://expressjs.com/en/4x/api.html#req.route) but I didn't find how could it be done in `koa-router`.

Thanks

**Comment by dKab** [comment]
Yeah, I also found myself looking for a way to get current route name from handler function.

**Comment by ruudud** [comment]
You can use the `ctx._matchedRoute` https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L315.

I suspect that you cannot count on this being around forever though..

**Comment by dKab** [comment]
@ruudud Yeah, thanks but I don't want to rely on undocumented private features.

**Comment by jbielick** [comment]
> I suspect that you cannot count on this being around forever though..

If these properties are removed we'll consider it a breaking change. Safe to use!
