### ISSUE TITLE
deprecated Support for generators will be removed in v3

### ISSUE THREAD

**Issue by EddieZhao** [alexmingoia/koa-router#343]
deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md t.js:19:6

**Comment by EddieZhao** [comment]
code:
```
var app = require('koa')();
var router = require('koa-router')();

router.get('/', function *(next) {...});

app
  .use(router.routes())
  .use(router.allowedMethods());
```

koa version:  "^2.2.0",
koa-router version: " ^5.4.0"

**Comment by dmitriiivashko** [comment]
For Koa 2.x use the 7.x version of `koa-router`. v 5.x is designed to be used with Koa 1.x

Koa 2.x is async / await + promise based. It's generators support is only for limited backward compatibility and is deprecated.

**Comment by muzishuiji** [comment]
how to resolve it？

**Comment by Extarys** [comment]
I have the same warning with version 7 (I was going to ask if this will be upgraded to support v3 but found this issue instead)

```
    "koa": "^2.3.0",
    "koa-controller": "^1.1.0",
    "koa-response-time": "^2.0.0",
    "koa-router": "^7.2.1",
    "koa-views": "^6.0.2",
```

> koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md server.js:37:5

Line 37 correspond to the second line of the following code:
```
router
  .get('/', function (ctx, next) {
      app.use(async function (ctx, next) {
        ctx.state = {
          session: this.session,
          title: 'app'
        };

        await ctx.render('index', {
          message: 'Hello world! <3'
        });
      });
  })
```

**Comment by mogita** [comment]
I'm using koa-router `7.2.1` with koa `2.3.0`, still getting the `koa deprecated Support for generators will be removed in v3` message. I use async/await all the time.

**Comment by arunrreddy** [comment]
I fixed this by using the following.
`"@koa/router": "^7.2.1"`

It should work for you as well.

**Comment by LarryJKarp** [comment]
I solve it by updating koa-router to the latest version

**Comment by wotterfree** [comment]
I fixed this buy using @koa/cors instead of koa-cors!
