### ISSUE TITLE
Unit Testing routes by checking ctx.body

### ISSUE THREAD

**Issue by dschinkel** [alexmingoia/koa-router#349]
I'm trying to figure out how I can test a route via **unit** test.  I figured I can set some stuff on the context but not sure how to then get the app to call it though.

Lets say you have this piece of code:

**api.js**
```

import router from 'koa-router';

const api = router();

api.get('/', async ctx => {
        let responseModel = await controller.findAll();

        ctx.body = responseModel;
    })

export default api;
```

I started out a **unit** (not integration) test but not quite sure how to really get the app to invoke the right route based on the uri:

```
it('returns a body with data', () => {
        app.context.url = './companies/companyHeaders';
       // somehow get the app to call the right get() based on a match of './companies/companyHeaders' and once it does, get() runs and I want to get a hold of the ctx.body somehow
       // const body = ??? (ctx.body)
       // expect(body).to.be.an('object');
       // expect(body.companyHeaders).to.be.an('array');
});
```

So what I care about is that the behavior in the get()...behavior here would be wiring up the returned data from the controller to the ctx.body worked ok, that the data was set on the context successfully by my code there (this could break, someone could always f that up, so this is a good test to have).  So essentially I wanna check this behavior, check the ctx.body after this statement completes:

```
ctx.body = responseModel;
```

And I _don't want the app to start_, in other words _I don't want to call app.listen()_ in this test because that would turn this test into an integration test.  This is a unit test here I'm trying to complete.

While I'll have integration tests this is still a good test to have on the unit test level regardless, and I can use it for outside-in TDD as well, as a starting point.

I wrote this a couple years ago but at the time I was using Koa 1 and koa-controller: http://code-zest.blogspot.com/2015/09/testing-koajs-request-context.html

**Comment by motet-a** [comment]
This is really hacky, but you can write something like this:

```js
const index = async ctx => {
  ctx.body = await Users.findAdd()
}

const show = async ctx => {
  ctx.body = await Users.findAdd()
}

export const router = new Router
router
  .param('id', ...)
  .get('/', index)
  .get('/:id', show)

export const actions = { index, show }

```

...and in a test file:

```js
import { actions } from './the-controller-file'

describe('users', () => {
  describe('index', async () => {
    // Do whatever you want with `actions.index`, for example:
    const dummyCtx = {}
    await actions.index(dummyCtx)
    assert(dummyCtx.status = 200)
  })
  
  describe('show', () => {
    // Do whatever you want with `actions.show`    
  })
})
```

It doesn't check the routes but you know, it’s not the right way to do it.

But please consider:

- this doesn't replace higher-level testing with something like superest,
- it’s far simpler to use supertest,
- there is no reason for it to fail in this kind of hackish unit test if it works with supertest.

(You can replace `supertest` by any other similar library)

**Comment by dschinkel** [comment]
I'm not talking about integration testing which is what using supetest is.  And I'm not talking about testing a controller.  I'm only talking about testing the routes setup and logic in those routes that might be calling the controller.  I'm testing that behavior, not the controller.  I already have tests around my controller layer.  But you could also have stuff go wrong in your router when assigning what's returned to ctx.body, and that's what I wanna test.  But anyway thanks.

**Comment by dschinkel** [comment]
I'm closing the issue, doesn't seem to be a way to do this.

**Comment by stevenhair** [comment]
I came up with a workaround, but I'm also looking for a more elegant built-in solution:

```javascript
function callRoute(route, ...args) {
    route.stack.forEach((mw) => mw(...args));
}

describe('Router', () => {
    describe('/', () => {
        let ctx;

        beforeEach(() => {
            ctx = {};
            callRoute(router.route('index'), ctx);
        });

        it('it returns hello world', () => {
            expect(ctx).to.have.property('body', 'Hello, world!');
        });
    });
});
```

If you're not using named routes, then you'll have to find your route using something like

```javascript
const route = router.stack.find((route) => route.path == '/');
```

**Comment by Yorkshireman** [comment]
@stevenhair what is `stack` on line 2?
