### ISSUE TITLE
A bug in Router#url (latest version)

### ISSUE THREAD

**Issue by HeavenDuke** [alexmingoia/koa-router#351]
When using the latest version, I came into an error when using **Router#url**, where it shows:
```plain
TypeError: Expected "0" to be defined
```

The usage is something like the following code:
```javascript
var app = new Koa();
var router = new Router({
    prefix: "/books"
});

var embeddedRouter = new Router({
    prefix: "/chapters"
});
embeddedRouter.get('chapters', '/:chapterName/:pageNumber', function (ctx) {
    ctx.status = 204;
});
router.use(embeddedRouter.routes());
app.use(router.routes());
var url = router.url('chapters', { chapterName: 'Learning ECMA6', pageNumber: 123 });
```

I'm pretty sure that the usage is correct since everything worked fine in the old version. And after debugging I've found that there is a slight difference in **Router#use** between the two version, where variable **path**'s initial value is set to:

```javascript
var path = '(.*)';
```
instead of nothing.

This leads to some redundant parameter requirements after compilation with **path-to-regexp** package, and that is where **'0'** in the error message came from.

I tried to fix this, but resetting path to old version will lead to failure in unit test, so I tried to eliminate its influence within **Router#url** by replacing:

```javascript
var url = this.path;
```
in **Layer#url** to:
```javascript
var url = this.path.replace('\(\.\*\)', '');
```

After this everything seems to be working fine, with all unit test passed locally.

By the way, there is another thing that I'm not very sure. In the old version, when using this component along with Koa, I can access router object with a ctx object in the following manner:

```javascript
router.get('book-detail', '/books/:book_id', function *() {
     // some code...
});
router.post('create-book', '/books', function *() {
    // some code...
    this.redirect(this.app.url('book-detail', {book_id: book.id}));
});
```

but it seems that this is not okay with Koa2, since router is not included within ctx(Debugging showed no related stuff). To make sure that this manner still works, I append the router object to ctx. This leads to the following usage:
```javascript
router.get('book-detail', '/books/:book_id', function (ctx) {
    // some code...
});
router.post('create-book', '/books', function (ctx) {
    // some code...
    ctx.redirect(ctx.router.url('book-detail', {book_id: book.id}));
});
```

I'm still freshman in this field so I'm not very sure if the stuff above is really some sort of bug. If so, I've launched a pull request #350, hoping it will help. Thanks~

**Comment by jbielick** [comment]
#350 is merged. Does that resolve the issue?

**Comment by forrestjt** [comment]
I've just come across this issue, it looks like 
`var url = this.path.replace('\(\.\*\)', '');`
only replaces the first instance of (.*)
changing it to /\(\.\*\)/g seems to have fixed it
GH-407
