### ISSUE TITLE
Switch default branch to `master`

### ISSUE THREAD

**Issue by marvinhagemeister** [alexmingoia/koa-router#352]
Now that `koa@2` is out the door we should switch the default branch in this repo to `master`. The `5.x` branch seems to be targeted at `koa@1` users.

**Comment by jbielick** [comment]
need special privileges for this one /ping @alexmingoia

**Comment by jbielick** [comment]
@alexmingoia Can you change the default branch to `master` or give me the ability to do so?

**Comment by alexmingoia** [comment]
@jbielick It should be switched now.

**Comment by jbielick** [comment]
Thank you!
