### ISSUE TITLE
Request is responded ignoring `await` in router with error "AssertionError: headers have already been sent"

### ISSUE THREAD

**Issue by ginozhu** [alexmingoia/koa-router#353]
I have following codes with koa-router, using async/await to return response only after some asynchronous actions.
However whenever the code reaches await, it always return a 404 to client and server would still execute the following codes and when reaches ctx.status=200, there will be an error raised saying "AssertionError: headers have already been sent".

```
router.post('/issue',
  async (ctx) => {
    await promiseSleepFunc(1000);
    ctx.status = 200;
    ctx.body = 'Success!';
  });
```

**Comment by noob9527** [comment]
It seems like I run into the same issue, Can you share your solution? @ginozhu

**Comment by crcrcry** [comment]
How did you solve this problem.

**Comment by ginozhu** [comment]
@crcrcry It was sth wrong with my middlewares, not related to koa-router
