### ISSUE TITLE
how to match routes with some special chars?

### ISSUE THREAD

**Issue by Cheonsoon** [alexmingoia/koa-router#355]
```javascript
router.get('/customer/:customer_id/ss/orders?q=close-time:":close_time_range"', async (ctx, next) => {
```

`/customer/:customer_id/ss/orders?q=close-time:":close_time_range"` is my expected routes, and I use `/customer/100/ss/orders?q=close-time:"heheda"` to request it, which always return 404. (my testing code works well, too. As I use them to test other routes, successfully)

While I debug it, and founds out that the extracted stack's paramNames & regexp are all right.
![image](https://cloud.githubusercontent.com/assets/1361794/26452052/13eb60da-4191-11e7-9109-9a1415b643f6.png)

**Comment by jbielick** [comment]
The query string in your request URL must be uri-encoded. `:` and `"` are not valid characters in the query string portion of the URL.

`?q=close-time:":close_time_range"` must become `?q=close-time%3A%22heheda%22`

[more info](https://stackoverflow.com/questions/2366260/whats-valid-and-whats-not-in-a-uri-query)
[more info](https://bytes.com/topic/html-css/answers/96296-double-quotation-mark-within-url)

**Comment by Cheonsoon** [comment]
Haha, it's my mistakes, and thanks for your detailed reply
