### ISSUE TITLE
router.get(path, middleware, otherMiddleware) seems to execute in wrong order when using async/await

### ISSUE THREAD

**Issue by rw3iss** [alexmingoia/koa-router#356]
Heyas,

 If I setup a get route using the traditional generators, the order is preserved correctly, but when I switch to using async/await, the order seems to be reversed.

 Here is the example code working:

```
router.get(
	'/users/:id',
	function* (next) {
		console.log("adding user...");
		this.user = { user: 'test' };
		yield next;
	},
	function* (next) {
		console.log('user', this.user);
		this.body = this.user;
	}
);
```

Which outputs:
> adding user... 
> user { user: 'test' }

But when I change it to use async/await, see what happens:

```
router.get(
	'/users/:id',
	async function (next) {
		console.log("adding user...", next);
		this.user = { user: 'test' };
		await next;
	},
	async function (next) {
		console.log('user', this.user);
		this.body = this.user;
	}
);
```

Outputs:
> user undefined
> adding user... Promise { undefined }

Am I doing something wrong here?

**Comment by jbielick** [comment]
What version are you using? If you're using version 7, which is compatible with async / await and koa 2, your middleware signature is wrong. The arguments are `async function(ctx, next)` and you must await `next`. In your example you might be awaiting. If you're using koa-router version 5, your first example is correct. 

https://github.com/alexmingoia/koa-router/tree/master/#migrating-to-7--koa-2

**Comment by rw3iss** [comment]
Thank you. Yeah I was using koa-router@5 and tried all manner of (ctx, next) signatures, but nothing was working. Didn't realize I was so far behind on the version. Works fine, thanks again!
