### ISSUE TITLE
Example with Node v8

### ISSUE THREAD

**Issue by krokofant** [alexmingoia/koa-router#357]
I'm trying to use the basic example with Node v8 like below but it seems nothing is executed on that route. It does work if the `function*` is instead `function` or `async function`.

Care to give me some insight into what the issue is and an explanation as how this works? I'm not sure if this is an issue or if I'm missing something.

```javascript
const Koa = require('koa');
const app = new Koa();

var Router = require('koa-router');
var router = new Router()

router
    .all('/', function* (next) {
        console.log('hello')
        this.body = 'Hello World!';
    });

app
    .use(router.routes())
    .use(router.allowedMethods());

app.listen(3000);
```

**Comment by jbielick** [comment]
What version of `koa` and `koa-router` are you using?

**Comment by krokofant** [comment]
@jbielick Latest:
koa: "2.2.0"
koa-router: "7.2.0"

**Comment by jonaspm** [comment]
Try to use normal function instead of generator.

**Comment by krokofant** [comment]
@jonaspm Perhaps I wasn't clear enough. Both function and async function works. This issue is in regards to how one should use the callbacks since the README specifies using generators which does not seem to work for me with Node v8.



_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jbielick** [comment]
When you're reading the README are you on the `master` branch or the `5.x` branch? The default right now is not master (latest release, 7.2.0). I don't think generator functions are supported in koa 2.2

**Comment by krokofant** [comment]
@jbielick Thanks! I think I might have missed what branch I looked at.

**Comment by Dragon-Rider** [comment]
@jbielick I met the same problem. It can support async but generator. Thanks~
