### ISSUE TITLE
router does not await async functions

### ISSUE THREAD

**Issue by mtkage** [alexmingoia/koa-router#358]
Hi

I am using the following versions
nodejs v7.7.1
+-- koa@2.2.0
+-- koa-router@7.2.0

My problem is that the router returns without awaiting for the async function to resolve. The sample code is below:
```
router.get('/relay', async (ctx) => {
  const token = await relay();
  ctx.status = 200;
  ctx.body = token;
});

async function relay() {
  return await timeout(5000);
}

async function timeout(delay) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("random");
    }, delay);
  });
};
```

I can see from my logs that the route `/relay` returns immediately with a `404`. The timeout function is called asynchronously and when it tries to set the ctx status the following error is thrown.
`AssertionError: headers have already been sent`

There does not seem to be a clear way to achieve what I want. I simply want to await an asynchronous function and return once it is resolved. How can I do this?

**Comment by jbielick** [comment]
Here's a test case I created on my machine with 
node 7.8
koa 2.2
koa-router 7.2

```js
const Koa = require('koa');
const Router = require('koa-router');

const app = new Koa();
const router = new Router();

router.get('/relay', async (ctx) => {
  const token = await relay();
  ctx.status = 200;
  ctx.body = token;
});

async function relay() {
  return await timeout(5000);
}

async function timeout(delay) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("random");
    }, delay);
  });
};

app.use(router.routes());

app.listen(3001);
```

And it seems to work fine:
```
┌[josh@HAL9000] [7]
└[~]> time curl localhost:3001/relay
random
curl localhost:3001/relay  0.00s user 0.00s system 0% cpu 5.030 total
```

Is this a representative sample of the code where you're having the issue?

**Comment by mtkage** [comment]
Yes. It does seem to be representative of my code. And it is working on my machine as well. Let me take another look at the code. I must be doing something wrong with the middlewares. Thanks for your time and help!

**Comment by crcrcry** [comment]
How did you solve the problem?

**Comment by ccsang** [comment]
@mtkage I meet the problem too， could you tell me how you fixed it? Thanks a lot.

**Comment by mtkage** [comment]
@crcrcry @ccsang The problem usually lies in the code that you must be calling. When using async await, you need to make sure that the entire call stack uses the same paradigm. If any of the functions in the stack do not await an async function, the desired result is not seen.

Check if you are using some external libraries that might be triggering functions asynchronously.

**Comment by ccsang** [comment]
@mtkage I examined my middlewares,  finally found out the mistake I made as you said,  thanks.

**Comment by wzdxy** [comment]
I also encountered a similar problem.  I got a 404 error as long as I called an asynchronous function in the route. But if I don't call any asynchronous function, there's no problem
The reason is that one of a middlewares does not use the `await` modifier when calling the `next()` method. ( **Even if it doesn't seem to have anything to do with the router** )
I guess this may cause the middleware to continue executing without waiting for the return result of the next middleware.
eg:
```js
// this is wrong
app.use(function (ctx, next) {
    ctx.set("Access-Control-Allow-Origin", "*");
    next();
});
// this is right
app.use(async function (ctx, next) {
    ctx.set("Access-Control-Allow-Origin", "*");
    await next();
});
```

**Comment by a932455223** [comment]
@mtkage I meet the problem too,thank you

**Comment by rosshadden** [comment]
This is such a weird problem because the workaround that @wzdxy posted doesn't seem like it should even be related.  But it does fix it.

**Comment by jbielick** [comment]
@rosshadden you need to either `await next();` or `return next();` otherwise Koa has no idea that you're doing something async and your function won't wait on downstream middleware.

**Comment by rosshadden** [comment]
Haha I just had the realization that it actually makes perfect sense and came back here to update accordingly. But you beat me to it.

**Comment by DevelopSmith** [comment]
@wzdxy @jbielick you guys saved my day

**Comment by boardgames** [comment]
>     "koa": "^2.5.1",
>     "koa-router": "^7.4.0",
and code 
`router.get('/relay', async (ctx) => {
  const token = await relay();
  ctx.status = 200;
  ctx.body = token;
});

async function relay() {
  return await timeout(5000);
}

async function timeout(delay) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve("random");
    }, delay);
  });
};`
does not work for me, answer like

>   --> GET /relay 404 5ms -
> 222 'random'

but if remove Promise - works fine.

**Comment by Oyelaking** [comment]
@mtkage @wzdxy Thanks guys! This has been giving me a headache all day. After reading the comments, I went and found the middleware that wasn't an Async function. Geez! A whole freaking day spent on this!

**Comment by liweijian1** [comment]
@mtkage @wzdxy Thanks guys!

**Comment by daGaiGuanYu** [comment]
You must ```await``` all the ```next()```!!!
