### ISSUE TITLE
204 is not okay for OPTION status code (this breaks angular2)

### ISSUE THREAD

**Issue by frederik-sevenval** [alexmingoia/koa-router#359]
Our angular2 app is not working, because the koa-router sends 204 responses for the OPTION xhr calls.

Then I quickly searched for correct status codes for OPTION calls and quickly found this answer:
https://stackoverflow.com/a/31256072

koa-router incorrectly dosn't provide the Content-length Header, which it should (and therefore send a 200. not a 204).

**Comment by fl0w** [comment]
This also messes up Safari https XHR requests - nothing that really breaks anything but they're never closed.

**Comment by jbielick** [comment]
Thanks for bringing this up. I came to the same conclusion after reading the RFCs. 

`v7.2.1` includes this fix and is published to NPM. 

The CORS preflight response now looks like this:

```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Content-Length: 0
Allow: HEAD
Allow: GET
Date: Sat, 17 Jun 2017 15:47:04 GMT
Connection: keep-alive

```

**Comment by timbru31** [comment]
This is IMO a breaking change for anyone checking if the response code is 204.

**Comment by jbielick** [comment]
Preflight requests are not handled in user-land, they're executed by the browser. Are you considering a different case? Could you expand on that case?
