### ISSUE TITLE
Performance issues with nested router

### ISSUE THREAD

**Issue by nasushkov** [alexmingoia/koa-router#363]
I encounter significant performance degradation when using nested Router with prefix:

`const apiRouter = new Router({prefix: '/api'})
...
apiRouter.get('/forge/layouts/:syncId', querySyncStatus)
`
Then I add it to the root router:

` rootRouter
      .use(apiRouter.routes(), apiRouter.allowedMethods())`

When router tries to resolve the path /forge/layouts/:syncId it slows down on each subsequent query.  I found that layer.match(path) for each layer of the nested router is the real bottleneck. Here are path and regexp for the layer object for this particular root:

> path: "(.*)(.*)(.*)(.*)(.*)/api/forge/layouts/:syncId"
> regexp: /^((?:.*))((?:.*))((?:.*))((?:.*))((?:.*))\/api\/forge\/layouts\/((?:[^\/]+?))(?:\/(?=$))?$/i

**Comment by YanLobat** [comment]
Can you give more detailed example please? @nasushkov

**Comment by tomatau** [comment]
I'm noticing a similar behaviour, although it's sporadic for me, some requests take up to 30 seconds to hit the route and others are near instant for the same request.

I'm guessing a combination of koa mount passing the prefix there and without the prefix option in koa router will not have the same issue.

**Comment by jbielick** [comment]
Can you reopen with any profiling stats / data collected?
