### ISSUE TITLE
Nested routers behaviour changed in koa@7

### ISSUE THREAD

**Issue by pmrukot** [alexmingoia/koa-router#369]
Hi 👋 

I've encountered an issue while migrating to koa@2 with koa-router@7. Im nesting my routes like these:

```JS
const router1 = new Router({prefix: '/firstPrefix'});
const router2 = new Router({prefix: '/secondPrefix'});

router2.use(resourceRouterA.routes());
router2.use(resourceRouterB.routes());
router2.use(resourceRouterC.routes());

router1.use(router2.routes());
```

And I've noticed that the paths in my routes changed, to be specific `(.*)` was added to them. So the paths looked like below:

Before (koa@5):
`/firstPrefix/secondPrefix`

After (koa@7):
`/firstPrefix(.*)/secondPrefix(.*)`

And my routes broke as you may guess. (needed to add additional dummy string to match syntax)

So I went to the sources:

koa-router@5:
https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L221
https://github.com/alexmingoia/koa-router/blob/5.x/lib/router.js#L258

koa-router@7:
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L246
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L276

In koa-router@5 there is:
```
var path = '(.*)';
(...)
router.register(path);
```

while in koa-router@7:
```
var path;
(...)
router.register(path || '(.*)');
```

The problem is, that in koa-router@7 path is always truthy, and the prefix of `(.*)` is being set while no string is specified in first argument:
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L257
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L265

I've also found some relevant issues here:

https://github.com/alexmingoia/koa-router/issues/155
Similar to mine, I've changed the routes declaration to:
```JS
const router1 = new Router({prefix: '/firstPrefix'});
const router2 = new Router({prefix: '/secondPrefix'});

router2.use('', resourceRouterA.routes());
router2.use('', resourceRouterB.routes());
router2.use('', resourceRouterC.routes());

router1.use('', router2.routes());
```

And now it seems to work as before. But the discussion in the issue above was just cut, with no explanation or followup if this is a bug or not.

I've also found these ones that may be relevant: 
https://github.com/alexmingoia/koa-router/commit/866562034cb588f0cbfa5861ddde1aec6fb75930
https://github.com/alexmingoia/koa-router/pull/260

**So the question: is this intentional behaviour?** I haven't found anything in docs about this change.

**Comment by YanLobat** [comment]
Sorry If I misunderstood you, but It seems that #244 is relevant to your issue.

**Comment by amangeot** [comment]
@pmrukot does this solve your issue?

```
for (let layer of router.stack) {
  layer.path = layer.path.replace(/\(\.\*\)/g, '')
}
``` @ the main router
