### ISSUE TITLE
Possible to set a timeout on a specific route?

### ISSUE THREAD

**Issue by nitrocode** [alexmingoia/koa-router#379]
Looking for an easy way to set a timeout on specific routes. Is this possible without writing a custom module?

**Comment by jbielick** [comment]
A nice way to handle this would be to pass a timeout middleware function in front of your route handler so you can wrap the downstream handler in a timeout. This is akin to profiling middleware. Refer to the "multiple middleware" section of the readme or app.use for nesting routers with their own middleware.
