### ISSUE TITLE
Why does downstream middleware run after a route match?

### ISSUE THREAD

**Issue by cquillen2003** [alexmingoia/koa-router#382]
I am trying to separate routes that require authorization from routes that don't as shown below.  However, a match in the "pages" router does not stop the request from "flowing" to the authorization route handler, so I am getting a 401 error on my login page.

```javascript

//Public routes such as '/login'
app.use(pages.routes()); 

//Require authorization beyond here
app.use(async (ctx) => {
    var token = ctx.cookies.get('AuthSession');
    try {
        var decodedToken = jwt.verify(token, 'shhhhh');
    } catch (error) {
        ctx.throw(401);
    }
    await next();
});

//Private routes
app.use(private.routes());

```

**Comment by YanLobat** [comment]
@cquillen2003 If you are trying to use auth middleware separately why do you use it as a global middleware?(`app.use`)

Also I recommend to [check](https://github.com/koajs/koa/blob/master/docs/error-handling.md#try-catch) error handling in koa2 middlewares

**Comment by cquillen2003** [comment]
Disregard.  A matched route does end the request.  I had additional requests being triggered.
