### ISSUE TITLE
should accurate path first?

### ISSUE THREAD

**Issue by Tang-RoseChild** [alexmingoia/koa-router#388]
there are two routes:
```
router.post('/:id', addStock);
router.post('/list', allStocks);
```
if request  accurate path '/list' by post, such as ``` curl -XPOST :10011/list```, it will router to ```addStock```, not ```allStocks```, and there is no way to ```allStocks```controller.
#### Q: should the accurate path be first?

---------
## backgroud
node version:
v8.2.1
koa version:
2.3.0
koa-router version:
7.2.1

### demo code (typescript)
```
import * as KoaRouter from 'koa-router';
import * as Koa from 'koa';
let router = new KoaRouter();



async function allStocks(ctx: Koa.Context) {
    ctx.body = 'hello, list all stocks'
}

async function getStock(ctx: Koa.Context) {
    ctx.body = 'get stock '
}

async function deleteStock(ctx: Koa.Context) {
    ctx.body = 'delete stock'
}

async function updateStock(ctx: Koa.Context) {
    ctx.body = 'update stock '
}

async function addStock(ctx: Koa.Context) {
    ctx.body = 'add stock '
}
router.get('/:id', getStock);
router.delete('/:id', deleteStock);
router.put('/:id', updateStock);
router.post('/:id', addStock);
router.post('/list', allStocks);

let app = new Koa();
app.use(router.routes()).listen(10011);
router.stack.forEach((route) => {
    console.log(route.path);
});
```

**Comment by Mensu** [comment]
How about moving ``router.post('/list', allStocks)`` in front of the routes for ``/:id`` ?

```js
router.post('/list', allStocks);
router.get('/:id', getStock);
router.delete('/:id', deleteStock);
router.put('/:id', updateStock);
router.post('/:id', addStock);
```

**Comment by Tang-RoseChild** [comment]
@Mensu it works, thanks.
But there is a little problem when the router split into different files, we always export the router,using ```router.routes()``` for loading, don't care about the router sequence. 
So, should accurate path be first is much better?

**Comment by Mensu** [comment]
@Tang-RoseChild It seems that this is an intentional design as of v7.0.0, as documented in [README](https://github.com/alexmingoia/koa-router/tree/master#migrating-to-7--koa-2) to be express-compatible.

> Middleware is now always run in the order declared by .use() (or .get(), etc.), which matches Express 4 API.

I am not sure whether ``koa-router`` before v7.0.0 uses accurate path first policy. Besides, there seem to be related issues as well: #261

**Comment by Tang-RoseChild** [comment]
@Mensu Thanks
