### ISSUE TITLE
Did I use koa-router in a wrong way?

### ISSUE THREAD

**Issue by lzszone** [alexmingoia/koa-router#389]
here is the situation:
I use a nested-router to handle with the request,
but I found out that the router.routes() return a sync function,
and I wrote every child-router to a async function, like:
```javascript
xRouter.get('/', async function(c, n){})
```
It's OK..BUT
if I put it in a normal position, like:
```javascript
app.use(async function(c,n){})
app.use(mainRouter.routes())
app.use(async function(c,n){})
```
then all error in the router will not be unhandled, I had to write like this:
```javascript
app.use(async function)
app.use(async function(c,n){
await next();
...
})
app.use(mainRouter.routes())
```
this way is OK,

but when I was trying to redirect ...
```javascript
const Router = require('koa-router');
const registerRouter = new Router();
registerRouter
  .get('/mobile', async (ctx, next) => {
    let code = ctx.query.code;
    if(code) {
      ctx.data.regCode = code;
    }
    ctx.data.getcode = false;
    ctx.template = 'interface_user_register.pug';
    next();
})
  .all('/', async (ctx, next) => {
    ctx.response.redirect('/register/mobile');
    next()
  })
module.exports = registerRouter;
```
it didn't work... the next middleware excuted still,
and the page was 500, because of lacking of some key data, url didn't change either
I think that the redirect method should send a response immediately...and throw an error maybe(response has sent already)
**question:**
1. can I put the main router middleware anywhere?
2. how can I redirect req to somewhere in a child-router

so....HELP!!

**Comment by Mensu** [comment]
The context of the question about the position of ``mainRouter.routes()`` is hard for me to understand...

> I think that the redirect method should send a response immediately

Nope, that's not how Koa works. Don't get confused with Koa and Express. The ``redirect`` method just sets response content without actually sending the response.

BTW the ``next()`` looks bad style to me. You might like to use ``return next()`` or ``await next()`` instead.

**Comment by lzszone** [comment]
@Mensu mainRouter are used to add some data to the ctx in my app, it does not render anything,
rendering is handled by the next middleware of the app,
which I think should be below(after) the mainRouter,
but router.routes() returns a sync function,
that causes if any middleware(called after mainRouter) threw an error, 
the error will be a 'UnhandledRejection', 
I put 
```javascript
app.use(async (ctx, next) => {
  try{
    await next()
  } catch(e){}
})
```
in the top of my app, if I use router that way , it won't catch anything,
only if I put the router to the last position...error will be caught
```javascript
//right in logic, but can't catch anything..
app.use(async function(c,n){})
app.use(mainRouter.routes()) //get data
app.use(async function(c,n){})// render the data and send
//strange but works
app.use(async function)
app.use(async function(c,n){
await next();
//await router gets data
...//then render
})
app.use(mainRouter.routes()) //get data
```
I considered about 'next()' and 'await next()',but i don't know what it await for...so i next(), just to avoid something unknown happen...if nothing gonna happen, await is cool...and that's why i chose Koa :D,
Thank you!!

**Comment by Mensu** [comment]
> but router.routes() returns a sync function,
> that causes if any middleware(called after mainRouter) threw an error,
> the error will be a 'UnhandledRejection',

``router.routes()`` returning a sync function is by no means the cause of the unhandled rejection. Unhandled rejections are usually caused by a ``Promise`` that we forget to register an error handler on.

For example, as I said, a ``next()`` that was used without ``return``, ``await``, or without an error handler as in ``next().catch(errHandler)``, may be the real cause of the unhandled rejection.

If you don't await or return ``next()``, chances are that the response would be sent **before the following middlewares completing its execution**. After the response is sent, errors would be thrown when you try to set some property of ``ctx`` in the logic of the following middlewares.

> I considered about 'next()' and 'await next()',but i don't know what it await for

I don't think it is something you can figure out by your own consideration. You should **learn how ``Koa`` works** by reading its documentations as well as understanding this [troubleshooting](https://github.com/koajs/koa/blob/1e81ea36910d6dc599f8868e0e31443f63399eba/docs/troubleshooting.md#troubleshooting-koa): what's wrong with the problematic codes, and why the solutions work.

**Comment by Mensu** [comment]
@lzszone 

Here is an example that may help:

```js
const app = new (require('koa'))()
app.use(async (ctx, next) => {
  console.log(1)
  try {
    await next()
  } catch (e) {
    console.log(2, e)
  }
})
app.use(async (ctx, next) => {
  console.log(3)
  // toggle between 'await next()' and 'next()' and check out the output
  // await next()
  next()
  console.log(4)
})
app.use(async (ctx, next) => {
  console.log(5)
  throw new Error('unhandled!')
})
app.listen(3000)
```

**Comment by lzszone** [comment]
@Mensu Yeah, it's my fault,  I replaced all `next()` to `await next()` in the mainRouter as you say,
everything goes well...
**多谢带喽**
