### ISSUE TITLE
Log a warning if a route would be unreachable

### ISSUE THREAD

**Issue by bschlenk** [alexmingoia/koa-router#394]
Given this example:

```javascript
router.get('/:id', fetchItem);
router.get('/list', fetchAllItems);
```

A warning should be logged that /list is an unreachable route. I just spent a good hour or two trying to figure out why my route wasn’t being called. If a warning was logged it would have been immediately obvious that I just needed to move the specific route above the parameterized one.

**Comment by jbielick** [comment]
I haven't seen any +1s on this so I'm tagging it as an enhancement and closing for now. I think the PR adds too much code for something that adds a little bit of convenience. I do think better logging and a visualization of the available routes may assist in this issue and I'll keep that in mind if there's a rewrite or way of adding those developer experience features to the app without adding the complexity.
