### ISSUE TITLE
Inner redirect

### ISSUE THREAD

**Issue by matoous** [alexmingoia/koa-router#398]
Hello!

I would like to redirect some pages internaly, e.g. I would like to keep URL as requested but change what gets executed. I use middleware for this purpouse:
```
router.use(async function (ctx, next) {
// ...some code
    ctx.path = newPath
// ...some code

  await next()
})
```

But this doesn't work, what is the right way to do this? Is it even possible?

Thank you,
Matous

**Comment by zyl1314** [comment]
@matoous i guess ctx.res.redirect will work
