### ISSUE TITLE
when i run node index.js cannot do anything in koa-router 7.3

### ISSUE THREAD

**Issue by zeroHu** [alexmingoia/koa-router#402]
the code is copy the example , and version in the pircture . when i run the code and  die . no any error . what's wrong ?

![image](https://user-images.githubusercontent.com/14057313/33548032-d6603984-d920-11e7-8d07-f0f34c0ef4b8.png)
![image](https://user-images.githubusercontent.com/14057313/33548053-e5ddad10-d920-11e7-95b7-ac9cf7f156ed.png)
![image](https://user-images.githubusercontent.com/14057313/33548090-011d71a0-d921-11e7-8fc7-fa40cd2b15c9.png)
![image](https://user-images.githubusercontent.com/14057313/33548112-1b990922-d921-11e7-935c-bd69bf6fb111.png)

**Comment by wachunei** [comment]
At the end of your example code add:

```js 
app.listen(3000);
```

[Check this "Hello World" example from koa](https://github.com/koajs/koa/blob/master/docs/api/index.md#application).
