### ISSUE TITLE
router.use did not strip the baseUrl from ctx.path

### ISSUE THREAD

**Issue by magicdawn** [alexmingoia/koa-router#404]
```js
router.use('/api', (ctx, next) => {
  console.log(ctx.path)
  return next()
})
```

when  navigate to `/api/v1/foo`, `ctx.path` = '/api/v1/foo', the baseUrl `/api` is not removed from `ctx.path`, this make middlewares that use `ctx.path` are not working as expected.

like
```js
const serve = require('koa-static')
router.use('/public', serve(__dirname + '/some-folder'))
```

`/public/1.txt` should map to `__dirname + '/some-folder/1.txt'` but in this package, `/public` is not striped from ctx.path

**Comment by jbielick** [comment]
I don't think this is a feature of `koa-router`. Were there docs or an example that lead you to the conclusion "should map to"?

**Comment by magicdawn** [comment]
Em that's what express do

http://expressjs.com/en/starter/static-files.html
> To create a virtual path prefix (where the path does not actually exist in the file system) for files that are served by the express.static function, specify a mount path for the static directory, as shown below:

```js
app.use('/static', express.static('public'))
```

Since this module is named as `koa router`, I guess this feature need to be supported!
I have a module `impress-router` support this feature, but the team can not afford the risk of using it in production. 😢 So I'm requesting this.

**Comment by jbielick** [comment]
I think the issue lies in your `serve` function. This would not be normal behavior for the router itself.

**Comment by ladytellur** [comment]
@magicdawn you could try to apply `mount`/`serve` to app itself instead of router
`app.use(mount('/public', require('koa-static')('public')));`
