### ISSUE TITLE
[Question] Name from URL

### ISSUE THREAD

**Issue by mintyPT** [alexmingoia/koa-router#405]
We can do this:

```
router.get('user', '/users/:id', function (ctx, next) {
  // ...
});

router.url('user', 3);
// => "/users/3"
```

But can we do the opposite? Something like this:
```
router.name('/users/3');
// => ['user', {id: 3}]
```
Or even just the name would be enough

```
router.name('/users/3');
// => 'user'
```

**Comment by mintyPT** [comment]
After diving deeper into the project, I found router.match which solves my problem. Thanks.

**Comment by jbielick** [comment]
Glad to hear it! Sounds like a good choice.
