### ISSUE TITLE
Parent prefix ignored if nested router path is empty string

### ISSUE THREAD

**Issue by farwayer** [alexmingoia/koa-router#409]
```js
const nested = new Router().get('', (ctx, next) => {
  ctx.body = "nested";
  return next();
});

const router = new Router({prefix: '/v1'})
  .use(nested.routes());
```

Requesting `/v1` throws 404 error. Fault is in [`Layer.setPrefix()`](https://github.com/alexmingoia/koa-router/blob/v7.3.0/lib/layer.js#L215): `if ("")` is false in js

**Comment by amangeot** [comment]
Hello, try using `new Router().get('/', middleware) instead`
