### ISSUE TITLE
Several middlewares executed with nested routes

### ISSUE THREAD

**Issue by farwayer** [alexmingoia/koa-router#410]
```js
const nested = new Router()
  .get('/', (ctx, next) => {
    ctx.body = "root";
    console.log("root");
    return next();
  })
  .get('/test', (ctx, next) => {
    ctx.body = "test";
    console.log("test");
    return next();
  });

const router = new Router()
  .use(nested.routes());
```
GETting `/test` prints to console:
```js
root
test
```
It is really unexpected behaviour!
Maybe related to https://github.com/alexmingoia/koa-router/issues/369 because the problem is with setting `(.*)` prefix in `Router.use()` function.

One more wrong thing with this behaviour: GETting `/xxx` will execute `root` although it should throw 404.

```js
router.use('', nested.routes())
```
can be used as workaround.

**Comment by jbielick** [comment]
This should be fixed in 7.4.0

https://github.com/alexmingoia/koa-router/commit/ff15285aeff110652b26177446e859294fe1748a
