### ISSUE TITLE
can't get 'ctx.state.user' in koa-router

### ISSUE THREAD

**Issue by z2014** [alexmingoia/koa-router#421]
when i use koa-router and koa-jwt middleware,i can'i get 'ctx.state.user' in koa-router , but found in app.use,this is my code
```
// app.js
const product = require('./product.js)
app.use(
  jwt({cookie: config.authCookie, secret: config.secret})
)
app.use(product.routes())
app.use(async (ctx, next) => {
    console.log(ctx.state.user) // it get {id: 1}
}
```
```
// product.js
router.get('/product', async (ctx.next) => {
    console.log(ctx.state.user) // it got undefined
})
```
i want to know if ctx in router is defferent form ctx in app ?

**Comment by jbielick** [comment]
It definitely isn't different. `ctx` is always passed through to all middleware. 

This doesn't look right:

```js
async (ctx.next) => {
```

Was this just a typo or does the code have that?

I think that should be:

```js
async (ctx, next) => {
```

We have many tests asserting that `ctx` is passed properly throughout.

**Comment by jbielick** [comment]
Please reopen if you have a small test application that I can use to verify this doesn't work correctly or a test case that shows this library does not work correctly.

**Comment by chrisdel101** [comment]
Did U ever solve this? I have the same problem.
