### ISSUE TITLE
Use middleware for all routes except [...]?

### ISSUE THREAD

**Issue by haywirez** [alexmingoia/koa-router#426]
Wondering if there would be a way to exclude instead of include routes for `router.use([...], fn())`? 
Or would you rather use nested/different router instances for this?
Use case: API that has 3-4 public endpoints, the rest is protected

**Comment by amangeot** [comment]
I believe there is a ctx._matchedRoutes or something like this you could use for banning some routes

**Comment by jbielick** [comment]
This is really up to the way you construct your routers—this isn't something that really fits into the router library nicely without adding complexity for a small use-case.
