### ISSUE TITLE
Arguments order for router.param() middlewares: reusability and composability

### ISSUE THREAD

**Issue by amangeot** [alexmingoia/koa-router#427]
Hello,
it would be nice to have the following order for arguments of `router.param()` middlewares:
`(ctx, next, id) => {}` instead of `(id, ctx, next) => {}`

This enables the use of these middlewares for `router.use()` along with `router.param()`
This also allows for composition with `koa-compose` which expects context and next as first arguments

**Comment by jbielick** [comment]
Since this breaks the existing API it would only be possible to implement in a new major version of this library.

**Comment by amangeot** [comment]
It would be great, especially with the way .param() works: can only chain one on the same key (from what I experienced) and gets registered before middlewares chained with .use().

**Comment by jbielick** [comment]
Yeah that sounds like it would work well. I'll keep this in mind if I work on a new version. I've tagged this with "enhancement". Can we close this for now?

**Comment by amangeot** [comment]
Sure, thank you for accepting the enhancement.
