### ISSUE TITLE
.use middlewares are called before .param middlewares

### ISSUE THREAD

**Issue by amangeot** [alexmingoia/koa-router#428]
Hello,
Below, `middleware` is called before `paramMiddleware`.
```
router
 .param('id', paramMiddleware)
 .use(middleware)
 .get('/', handleRoute)
```
I don't think it is an expected behaviour, it makes it hard to chain middlewares with paramMiddlewares.

**Comment by jbielick** [comment]
This is expected behavior

**Comment by jbielick** [comment]
`.param` can only insert itself _before_ the middleware stack if it is called _after_ you have middleware registered:

See `.splice` in the below method:

https://github.com/alexmingoia/koa-router/blob/2f0372a9a624c338033f0873507ea99d009ac9bb/lib/layer.js#L177-L204

I can see how this isn't ideal, but I believe it's always worked that way. This is more of a feature request, this would be a breaking change and wouldn't make until a version like 8 or 9.

**Comment by amangeot** [comment]
Oh ok I see, any chance to add a line about this behaviour in the readme ?

**Comment by jbielick** [comment]
Since you're familiar with the issue and its limitations, could you pull request that addition?

**Comment by amangeot** [comment]
Sure I'll try to do it asap
