### ISSUE TITLE
405 Method not Allowed

### ISSUE THREAD

**Issue by shrinathprabhu** [alexmingoia/koa-router#436]
Hi,
I am getting 405 Method Not Found as response when using PUT and DELETE request using POSTMAN.
I have also used `app.use(router.allowedMethods());` and my routes.js file looks something like this

             router.get('/users/:id', getData)
                      .post('/users', postData)
                      .put('/users/:id', updateData)
                      .del('/users/:id', deleteData);

Also when I check response headers section in POSTMAN it shows

          Allow →HEAD, GET
          Connection →keep-alive
          Content-Length →18
          Content-Type →text/plain; charset=utf-8
          Date →Thu, 15 Feb 2018 05:25:36 GMT
          Vary →Origin

I've also tried all the possible solutions out there on internet and git issues but still no use
Please help me fix this.

**Comment by HebutJipeng** [comment]
hi, i have the same question, how do you fix it finally?

**Comment by shrinathprabhu** [comment]
@HebutJipeng  Actually I forgot to save the updated code. That's why I was getting that error
But again I would recommend following steps to follow:
1. Use router middleware in main file app.js as follows:
`app.use(router.routes())`
`app.use(router.allowedMethods())`

2. If above 2 middlewares are added and still method doesn't work then check the postman request
Check whether `url` and `method` are correct because most of the time during testing we either forget to change the METHOD or we mistakenly enter incorrect url

3. If above steps are correct and still it doesn't work then check the code.
Like suppose you have request in postman like `localhost:3000/users/123` with `PUT` method but in code you've just written `router.put('/:id', update);`, then again it'll not work unless you've set router prefix to '/users'. This was error in my case. Actually I did put prefix but I forgot to save the updated code and hence I was getting error. ALSO DON"T FORGET TO SAVE THE UPDATED FILE

4. If error still continues, then follow below steps:
a. Try updating everything like POSTMAN, NODE.JS and MAYBE BROWSER (IF YOU'RE USING DIRECTLY THROUGH UI)
b. Try checking each line of code to see whether app is defined properly, whether proper middlewares are included, etc.
c. Remove all dependencies using `npm uninstall --save` and install it again so that you get fresh and updated packages again
d. Try using loggers to get the logs and check where it is going wrong

Let me know if error still continues after following above all steps so that I can open this issue again
