### ISSUE TITLE
ctx.request.params ?

### ISSUE THREAD

**Issue by rocketspacer** [alexmingoia/koa-router#440]
Can we move the params object to ctx.request and just set a descriptor on ctx to get the params. It would be much nicer to work with.
```
exports.index = async ({ request, response }, next) => {
    response.body = request.params;
};
```

**Comment by jbielick** [comment]
`ctx` is available to set context for the request/response lifecycle for all middleware adding functionality. `ctx.request` isn't an object this library owns, and adding properties to it comes with an inherent maintenance cost and risk that the other authors won't use it later. I'd rather just stick to using `ctx` and assume nothing about the keys `koa` uses.
