### ISSUE TITLE
Multiple routes/pages for one router...

### ISSUE THREAD

**Issue by andreaslacza** [alexmingoia/koa-router#445]
Hi i have multiple pages on my homepage for example

`router.use('/', index.routes()) <- route for www.example.io/`
**pagination on the homescreen:**
`router.use('/page/:site/', index.routes()) <- route for www.example.io/page/2/`

**profile of the tv series (details like cover and likes):**
`router.use('/tvseries/:id/', index.routes()) <- route for www.example.io/tvseries/123/`
**profile of the tv series (information about episodes):**
`router.use('/tvseries/:id/episodes/', index.routes()) <- route for www.example.io/tvseries/123/episodes/`
`app.use(router.routes())`

i also tried this:
`router.use(['/', '/page/:site/'], index.routes())`
`router.use(['/tvseries/:id/', /tvseries/:id/episodes/], index.routes())`

but both doesnt work. it show me an **Not Found** error

**Comment by jbielick** [comment]
Could you fill out the following information?

---

node.js version:

npm/yarn version:

`facktory-worker` package version:

#### Code sample:


```js

```

#### Expected Behavior:



#### Actual Behavior:



#### Steps to reproduce the behavior or a test case:
