### ISSUE TITLE
Unary operators in url?

### ISSUE THREAD

**Issue by Freysi21** [alexmingoia/koa-router#449]
Hey

Loving koa. Just wanted to check if something like this

```javascript
Route.newRoute("/stuff", "get", (ctx: Router.IRouterContext) => this.controller.getAll(ctx)),
Route.newRoute("/stuff?detailed=true", "get", (ctx: Router.IRouterContext) => this.controller.getAll(ctx, true)),
```

Is possible or not? notice "?detailed=true"

**Comment by jbielick** [comment]
koa-router routes based on method a

**Comment by jbielick** [comment]
koa-router routes based on HTTP method and path only, no routing is built in to this library based on URL parameters. The question mark will be interpreted by path-to-regexp library. This library does not handle the regex matching of routes. Sorry.

**Comment by Freysi21** [comment]
Yeah I see now that it would be smarter too use something like query-string-handler for something like that. 

Again, Koa <3, can't express how much I'm loving this library.
