### ISSUE TITLE
ctx.params not being parsed when middleware is run.

### ISSUE THREAD

**Issue by NicTorgersen** [alexmingoia/koa-router#452]
I'm having an issue where in my middleware, the parameter from the route definition isn't available.

```javascript
// prehandleroutes.js
module.exports = function (app) {
  return async function (ctx, next) {
    const id = ctx.params.id // undefined

    console.log(ctx.params)            // returns { '0': 'api/data/1231231' }
    console.log(ctx._matchedRoute)     // returns 'api/data/:id'
    console.log(ctx._matchedRouteName) // returns 'nameOfRoute'

    await next()
  }
}

// routedef.js
const preHandleRoutes = require('./prehandleroutes.js')
app.router.use('*', preHandleRoutes(app))

app.router.get('nameOfRoute', 'api/data/:id', async (ctx, next) => {
  // pretending to do work
})
```

I need to exit execution BEFORE a route is run after being hit by a client because there are database transactions being run in my endpoints. `preHandleRoutes` checks ownership of resources, which is quite crucial to my application.

I don't feel like it's the right approach to manually parse the URL params, because koa-router obviously does this itself at some point in time.

**Comment by NicTorgersen** [comment]
So I did what I said would be possible. I pre-parsed the URL to get the ID I need using the most simple approach at https://github.com/pillarjs/path-to-regexp.

`const fromRouteId = pathToRegexp(ctx._matchedRoute).exec(ctx.captures[0])`

**Comment by jbielick** [comment]
If middleware is invoked whether or not a route matches, what would be the expected behavior? When a route matches, params are present? When a route does not match, params are simply not present?

What would your expectations be?

**Comment by NicTorgersen** [comment]
This was my initial line of reasoning, and exactly my expectation. At least it makes sense in terms of how I understand koa-router.

**Comment by cymen** [comment]
This changed, right? I'm trying to find my bug as I figured someone else hit this. But in koa-router 7.0.1, middleware has `ctx.params` parsed. But in current (right now that is 7.4.0), `ctx.params` is empty.

**Comment by NicTorgersen** [comment]
@cymen i used the solution here https://stackoverflow.com/questions/49689406/koa-router-getting-parsed-params-before-hitting-route
