### ISSUE TITLE
Always get 404 on route with Mongoose

### ISSUE THREAD

**Issue by Disorrder** [alexmingoia/koa-router#453]
This is the code of route. When I use commented `Promise`, it returns 123 in body. But with mongoose query it returns 404 status. Item in log founds good. But it seems router just ignore await and return 404 immediately. What am I doing wrong?
```javascript
router.get('/:id', async (ctx, next) => {
    // TODO check ownerId
    // var item = await Promise.resolve(123);
    var item = await Character.findById(ctx.params.id);
    // if (!item) return ctx.throw(404);
    ctx.body = item;
    console.log('hmm', item, ctx.response);
});
```

**Comment by jbielick** [comment]
It's best to reserve this board for issues related to the library. There are many tests asserting this behavior works correctly. I think you could find some help with mongoose on StackOverflow. I'm not familiar with that library.

**Comment by Disorrder** [comment]
Okay
https://stackoverflow.com/questions/49778683/koa-router-ignores-async-await-of-mongoose-and-return-404-always

**Comment by olivewind** [comment]
i got the same issue, @Disorrder  how to resolve it
