### ISSUE TITLE
Router.use() doesn't take in composed Router middleware as expected

### ISSUE THREAD

**Issue by jared-ross** [alexmingoia/koa-router#454]
## The problem
Router.use() doesn't work as expected with composed Router middleware:

For example with `routerA.use('/B', compose([routerB.routes(), routerB.allowedMethods()]))` 
Router B's routes won't be found.

## The context
I was trying to save myself some typing by adding an install method to the Router prototype:
```javascript
Router.prototype.install = function () {
    return compose([this.routes(), this.allowedMethods()]);
};
```
Admittedly this is a very minor use case.

## A minimal working example of the problem
```javascript
const Koa = require('koa');
const Router = require('koa-router');
const compose = require('koa-compose');

const app = new Koa();


const withComposeRouter = new Router();
withComposeRouter.get('/', function (ctx, next) {
  ctx.body = 'With compose. This route is not found.';
});

const withoutComposeRouter = new Router();
withoutComposeRouter.get('/', function (ctx, next) {
  ctx.body = 'Without compose. This route is found.';
});


// The 'With' Route doesn't work while the 'Without' Route does work.
const rootRouter = new Router();
rootRouter.use('/with', compose([withComposeRouter.routes(), withComposeRouter.allowedMethods]));
rootRouter.use('/without', withoutComposeRouter.routes(), withoutComposeRouter.allowedMethods);
rootRouter.get('/', function (ctx, next) {
  ctx.body = 'Root.';
});


// This works the same as the one underneath
app.use(rootRouter.routes(), rootRouter.allowedMethods());
// app.use(compose([rootRouter.routes(), rootRouter.allowedMethods()]));

app.listen(3003);
```

## What I believe is happening
The problem lies in that Router.use detects whether a middleware it receives is a router or not and acts differently on that: (in `lib/router.js`)

```javascript
  middleware.forEach(function (m) {
    if (m.router) {
      m.router.stack.forEach(function (nestedLayer) {
        if (path) nestedLayer.setPrefix(path);
        if (router.opts.prefix) nestedLayer.setPrefix(router.opts.prefix);
        router.stack.push(nestedLayer);
      });

      if (router.params) {
        Object.keys(router.params).forEach(function (key) {
          m.router.param(key, router.params[key]);
        });
      }
    } else {
      router.register(path || '(.*)', [], m, { end: false, ignoreCaptures: !hasPath });
    }
  });
```
There are benefits to this: it allows the routing to set itself up outside of the middle of a request.
This way of doing things also allows Routers to be middleware in other uses. 

## What should be done about it
This is a small but annoying problem in my context that I can deal with.
Possibly note in the documentation that routes don't work like middleware when used with other routes.

**Comment by jbielick** [comment]
Yeah, the nesting when using `use` is really confusing. When you nest with `use('prefix', nestedRouter.routes())`, the `nestedRouter` is detected and it is modified to include the prefix given. This modification has cause numerous bugs and the magic of knowing a router was passed when a function was actually returned by `routes()` really blurs the line of what ought and ought not happen when the router is turned into a middleware function.

I don't think this can be fixed without some serious work in 7, but I'll make sure to address this in version 8 (in progress).

Please reopen if there is action to take in the meantime.

**Comment by jonaskello** [comment]
I got this exact same situation, took me quite a while to figure it out. @jbielick perhaps some documentation could be added meanwhile this is fixed? I looked at the section about nested routers, and yes it shows an example of nesting routers only, but it is easy to think that you can use any middleware in that position. So perhaps a note under the nested routers section saying that  `router.use()` does not work with any middleware, just router objects.
