### ISSUE TITLE
validation rules

### ISSUE THREAD

**Issue by jeromew** [alexmingoia/koa-router#46]
It could be a cool addition to koa router to integrate a rule-matcher in its API :

```
step1: match the path with a regexp (using :notation of {notation})
step2: validate the rules according to a definition (path rules, query rules, post rules)
```

It should not be coded inside koa-router since koa-router could leverage on existing rule matchers such as https://github.com/spumko/joi. There are probably other out there and the best would be to have a `consolidate`for rule matchers if it does not already exist.

**Comment by DylanPiercey** [comment]
@jeromew You can try https://github.com/DylanPiercey/koa-prove - similar to Joi.
