### ISSUE TITLE
router.post 405 Method not Allowed

### ISSUE THREAD

**Issue by mt-ik** [alexmingoia/koa-router#461]
node.js version: v8.10.0

npm/yarn and version:  npm v5.6.0 and yarn v1.6.0

`koa-router` version: v7.4.0

`koa` version: v2.5.1

#### Code sample:

```js
const Koa = require('koa')
const Router = require('koa-router');
const app = new Koa()
var router = new Router()
app.use(bodyParser())
router.get('/', (ctx, next) => {
		debugger
		ctx.body = 'Hello World!';
	})
	.post('/users', (res, req, next) => {
		debugger
	})
// 初始化路由中间件
app.use(router.routes());
app.use(router.allowedMethods())
app.listen(config.port, () => {
	console.log(
		chalk.green(`成功监听端口：${config.port}`)
	)
})
```

#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:

```
http://localhost:3000/users
405 Method Not Allowed
```

**Comment by jbielick** [comment]
Could you explain the issue you’re seeing? You left the “expected behavior” blank and it isn’t clear what type of http request you’re making because you only provided a url.

**Comment by mt-ik** [comment]
Sorry, thank you very much for your remind
I use the post method to initiate a request to access the “users” route but keeps prompting 405 Method not Allowed

**Comment by Tcbun** [comment]
i have the same question

**Comment by Tcbun** [comment]
i think we have raised a stupid quesiton, post is nothing on your screen, because you used chrome or other browser, we should use postman you would get what you want
