### ISSUE TITLE
Cannot catch "405 Method Not Allowed". 

### ISSUE THREAD

**Issue by lzszone** [alexmingoia/koa-router#472]
node.js version: 10+

npm/yarn and version: 5+

`koa-router` version: 7.4.0

`koa` version: 2.5.2

My colleague asks me to put the error information into the response body, 
so I write an error handler like below:
```js
async function errorHandler(ctx, next) {
  try {
    await next()
  } catch(e) {
    ctx.body = {
      code: e.status.toString(),
      message: e.message
    }
  }
}
```
And then I found that `404` and `405` cannot be catched by the handler,
`404` is the default status of `Koa`, so I handle it manually.
But I think `405` should be catchable... Am I doing something wrong? : )

**Comment by lzszone** [comment]
And I wrote a simple example:
```javascript
const Koa = require('koa');
const Router = require('koa-router');

const router = new Router();
router.get('/', (ctx, next) => next());

const app = new Koa();

app
  .use(async (ctx, next) => {
    try {
      await next()
    } catch(e) {
      console.log(e)
    }
  })
  .use(router.routes())
  .use(router.allowedMethods());

app.listen(3000);
```
Then `POST` to `localhost:3000/`
It responds a `405`, but nothing print in the console.

**Comment by kosl90** [comment]
@lzszone there is nothing throwed, so you can catch nothing. The 405 is handled in allowedMethods. If you need a exception, please use `router.allowedMethods({throw: true})`. You can also customize the **MethodNotAllowed** implementation. Just look into the documentation: [allowedMethods](https://github.com/alexmingoia/koa-router/tree/071b26489cb5c1886b2f89894a4633b18e9822de#routerallowedmethodsoptions--function). :)

**Comment by lzszone** [comment]
I did not read the document carefully enough, that's my problem... thank you for the module and answering me!
