### ISSUE TITLE
How get the ctx.request.body when router.del() ??

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [alexmingoia/koa-router#473]
node.js version: 10.0.6

npm/yarn and version: 6.1.0

`koa-router` version: 7.0.1

`koa` version: 2.2.0

#### Code sample:

```
        $delete('/api/push/comments',{lang:this.props.lang,oid:[record._id.$oid]})
            .then((res)=>{
                console.log(res)
                alert(JSON.stringify(res))
            },err=>{
                console.log(err)
                alert(JSON.stringify(err))
            })
```
```
router.del('/comments',async(ctx,next)=>{
    let {lang,...opt} = ctx.request.body
    let push = new NewsdogPush(lang)
    console.log(ctx)
    try {
        let res = await push.delComments(opt)
        ctx.body = res
    } catch (err) {
        console.log(err)
        throw new Error(JSON.stringify(err))
    }
})
```
#### Expected Behavior:
I hope can get `lang & opt` from `ctx.request.body`

#### Actual Behavior:
But it's {}

#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:

```js
```

**Comment by jbielick** [comment]
`koa-router` does not parse request bodies. Are you using `koa-body` to parse the request body? `DELETE` requests don't typically have a request body and most servers ignore them. [This is the default behavior or koa-body](https://github.com/dlau/koa-body)

> strict {Boolean} If enabled, don't parse GET, HEAD, DELETE requests, default true

Please reopen if you believe there's an issue with `koa-router`. If you're still having trouble, try asking a question on stack-overflow.

**Comment by Mr-jiangzhiguo** [comment]
@jbielick 
yeah,I use `koa-body`, and I just remember that it need a parameter , but forgot which one is specific, thank you!
