### ISSUE TITLE
`prefix` seems to be broken

### ISSUE THREAD

**Issue by batrudinych** [alexmingoia/koa-router#496]
node.js version: 
10.15.1
npm version: 
6.4.1
`koa-router` version: 
7.4.0
`koa` version: 
2.7.0
#### Code sample:

```js
const Koa = require('koa')
const app = new Koa()
const Router = require('koa-router')

const ordersRouter = new Router({ prefix: 'orders' })

ordersRouter.get('/', ctx => {
  ctx.body = 'Orders'
})

app
  .use(ordersRouter.routes())

app.listen(3000)
```

#### Expected Behavior:

`localhost:3000/orders` responds with `Orders` string

#### Actual Behavior:

`localhost:3000/orders` responds with 404 Not Found

**Comment by ralyodio** [comment]
This looks correct to me.

**Comment by batrudinych** [comment]
@chovy does this work as expected on your machine? With certain versions in use

**Comment by bytesnz** [comment]
Are you just missing a `/` at the start of the prefix?

```diff
5c5
< const ordersRouter = new Router({ prefix: 'orders' })
---
> const ordersRouter = new Router({ prefix: '/orders' })
```

**Comment by batrudinych** [comment]
Thanks @bytesnz 
Awkward situation :) My bad

**Comment by bytesnz** [comment]
No problem. Glad that was it. Been there, done that. :smile:
