### ISSUE TITLE
Got 404 rather than 500

### ISSUE THREAD

**Issue by cecilcosta** [alexmingoia/koa-router#509]
node.js version: v12.4.0

npm/yarn and version: npm 6.9.0

`koa-router` version: 3.2.0

`koa` version: 2.7.0

#### Code sample:

```
module.exports.mycall = async (ctx, next) => {
  const object = await ObjectFinder.find(ctx.request.body.id); // this object doesn't exits and an exception is thrown.
  object.date = new Date();
  await object.save()
  ctx.status = 204
};

```

#### Expected Behavior:

As there was an exception the response code should be 500

#### Actual Behavior:

Got a 404, which makes no sense.

#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:

```
```

**Comment by divmgl** [comment]
There's not information in this PR to recreate this.

**Comment by cecilcosta** [comment]
Sorry I didn't see that this issue was created to a pull request rather than the project it self. I'll close this one and create a new issue.
