### ISSUE TITLE
Can you please give me npm and GitHub access?

### ISSUE THREAD

**Issue by niftylettuce** [alexmingoia/koa-router#513]
@ZijianHe I have emailed you multiple times and have not heard a response.  Please grant me ownership so I can help maintain this.

**Comment by niftylettuce** [comment]
My plan is to archive and deprecate the package and use the KoaJS org fork instead.

**Comment by shreyasminocha** [comment]
> My plan is to archive and deprecate the package and use the KoaJS org fork instead.

Yes, this needs to be done. Will installing `koa-router` install `@koa/router` automatically or would it show some sort of deprecation notice?

**Comment by TheWashiba** [comment]
@niftylettuce have you tried making a contact with github and npm support?

**Comment by niftylettuce** [comment]
I will do so, but I doubt they can do anything.

**Comment by niftylettuce** [comment]
Just did!

**Comment by giorgiosironi** [comment]
Should this repository be archived too through the Github settings, if it has been forked and won't be updated anymore?

**Comment by niftylettuce** [comment]
I reached out to GitHub and npm several months ago.

GitHub helped by making the fork a standalone repo (not a fork).

npm said they would follow up and help, but it has been several months since I heard word from them and no reply.  They said they would take action, but it does not appear they will do so.

If you would, please kindly reach out to support@npmjs.com and link them to this issue.  Perhaps something went wrong with their support system and my ticket was closed...

**Comment by karfau** [comment]
It looks like npm finally did the change. Is the plan to publish the same package under both names from now on?
Maybe this information can be added to the readme (the one visible in npm), so it's more obvious for people whether they can safely stay on `koa-router` forever or should switch to `@koa/router`.

**Comment by niftylettuce** [comment]
npm has given me control of this package, will do.
