### ISSUE TITLE
Error: Cannot find module 'koa-router'

### ISSUE THREAD

**Issue by xgqfrms** [alexmingoia/koa-router#528]
# Error: Cannot find module 'koa-router'

![image](https://user-images.githubusercontent.com/7291672/94507257-ea2ed680-0241-11eb-81b4-367b05491f9c.png)

## `koa-router`  !==  `koa-route`

```sh
# ✅ install OK 👍
$ yarn add koa-router   
```
https://www.npmjs.com/package/koa-router

```sh
# ❌ install by mistake 👎
$ yarn add koa-route
```

https://www.npmjs.com/package/koa-route

**Comment by ralyodio** [comment]
code?

**Comment by xgqfrms** [comment]
@chovy sorry for that mistake
