### ISSUE TITLE
hello, I have some trouble with koa-router

### ISSUE THREAD

**Issue by PerterPon** [alexmingoia/koa-router#70]
I use koa-router just like connect, but I found it din't work, here is my code in connect:
- connect.
  When I visit 'xxx.com/test', it'll through m1, then to m2.

```
app.use( '/', m1 );
app.use( '/test', m2 );
```
- koa-router.
  When I visit 'xxx.com/test', it just came to m2.

```
r1 = new KoaRouter();
r2 = new KoaRouter();
r1.get( '/', m1 );
r2.get( '/test', m2 );
app.use( r1.middleware() );
app.use( r2.middleware() );
```

or like this way.

```
app.use( KoaRouter( app ) );
app.get( '/', m1 );
app.get( '/test', m2 );
```

Is there some problem in my code? I want to log some access information.
Thank you every much.

**Comment by tyru** [comment]
@alexmingoia 

```
app.use('/api', authMiddleware, router.middleware());
app.use('/static', serve());
```

`app.use(function)` only takes 1 argument.
