### ISSUE TITLE
Nesting routers

### ISSUE THREAD

**Issue by jampy** [alexmingoia/koa-router#77]
I'm new to KOA and koa-router.

With KOA, I learned that I can nest handlers/middleware to add pre- and postprocessing so that I can do...

``` javascript
app.use(function*(next) {
  console.log("HTTP:", this.request.method, this.request.url);
  yield next;
  console.log("HTTP: END request");
});

app.use(function*(next) {
  this.body = "hello";
});
```

However, with koa-router this doesn't seem to be possible. I tried:

``` javascript
app.register("/ajax/:action", ["get", "post"], function*(next) {
  console.log(">>> AJAX");
  try {
    yield next;
  } catch (e) {
    this.body = "Exception catched";
  }
});

app.register("/ajax/:action", ["get", "post"], function*(next) {
  this.body = "Handling AJAX " + this.params.action;
});
```

However, in that case only the first registered handler gets called resulting in a "Not found" response (since the first handler does not generate any response).

Is this by design? If so, why is `next` still passed, then?

I think it would be great if nesting routed would be possible. In my case, the first handler should make sure that all AJAX requests are handled correctly. For example, when an exception is thrown in an downstream handler, this should still produce a valid JSON response indicating the error.

**Comment by Globik** [comment]
Where is .register from?

**Comment by alexmingoia** [comment]
https://github.com/alexmingoia/koa-router#routerregistername-path-methods-middleware--route

**Comment by Globik** [comment]
Thank you.
