### ISSUE TITLE
Add option to throw instead of sending 405, 501

### ISSUE THREAD

**Issue by paglias** [alexmingoia/koa-router#92]
I would like to have an error thrown instead of having the router respond with a 405 or 501 status on its own. So that I can catch it and deal with it differently.

**Comment by alexmingoia** [comment]
405 and 501 responses are separated into `.allowedMethods()` middleware in the new `4.0.0` release. Use `.allowedMethods({ throw: true })` to throw errors.

See https://github.com/alexmingoia/koa-router#module_koa-router--Router#allowedMethods

**Comment by paglias** [comment]
@alexmingoia thanks! do you have a changelog with breaking changes in 4.0.0?

**Comment by alexmingoia** [comment]
4.x is almost entirely backwards compatible with 3.x. The only breaking change for the public API is if you are creating a router specifically with both `new` and `app`. In that case, 4.x returns the router instance and 3.x returns the router middleware. However, most people mounted the router like `app.use(router(app))` which behaves the same in 4.x.

https://github.com/alexmingoia/koa-router/blob/master/history.md#400
