### ISSUE TITLE
Current approach to attach shared middleware

### ISSUE THREAD

**Issue by bitinn** [alexmingoia/koa-router#93]
Say I want to protect multiple routes using an auth module or handle errors on multiple routes using a common middleware, but try to avoid repeating them in routes. Do I need to use `koa-resource-router`? Or should I go with `koa-mount` to achieve filter/group like routing.

There were talks and PR related to matching multiple routes pre `koa-resource-router` split, not sure about the status quo now.

**Comment by alexmingoia** [comment]
You can use either per-route middleware or `koa-compose` with the router middleware:

```javascript
router.get('/protected', function *() { ... });
app.use(compose([authMiddleware, router.middleware()]);
```

or

```javascript
router.get('/protected', authMiddleware, function *() { ... });

**Comment by bitinn** [comment]
I should clarify, I meant matching multiple routes like https://github.com/alexmingoia/koa-router/issues/29

so everything under /protected/ path will go through authMiddleware, and similarly for error handling. Writing per-route is fine but quite tedious.

**Comment by alexmingoia** [comment]
Use `koa-mount` and `koa-compose` with multiple routers.

```javascript
var protectedRouter = new Router();
var publicRouter = new Router();

protectedRouter.get('/foo', function *() { ... });
protectedRouter.get('/bar', function *() { ... });

app.use(mount('/protected', compose([authMiddleware, protected.middleware()])));
app.use(public.middleware());
```

**Comment by bitinn** [comment]
got it, so multiple router is the right way 2015.
