### ISSUE TITLE
How to organize routes with koa-router in koa?

### ISSUE THREAD

**Issue by hwoarangzk** [alexmingoia/koa-router#95]
My code is as follows:
router.coffee
<pre>
Router = require 'koa-router'
router = new Router()

module.exports = router

router.get '/', (next) ->
	this.body = 'index'
	yield next

router.get '/koa', (next) ->
	this.body = 'the path is /koa'
	yield next

router.get '/hello', (next) ->
	this.body = 'hello world'
	yield next
</pre>

index.coffee:
<pre>
koa = require 'koa'
router = require './router'
app = koa()

app.use router

app.listen 3000
</pre>

I just wanna organize the routes like what I do in express. But in this way, it reported an error saying that koa's middleware needs a generator, and what I passed to app.use is not a generator. I also refered to koa-mount, if I use koa-mount, I have to pass the path as the first parameter like:
<pre>
app
  .use(mount('/v1', APIv1.middleware()))
  .use(mount('/v2', APIv2.middleware()));
</pre>

I want to write my routes config in a seperate file. How could I get this done with koa-router? Thank you

**Comment by coderhaoxin** [comment]
> it reported an error saying that koa's middleware needs a generator, and what I passed to app.use is not a generator

```coffee
app.use router. middleware()
```

**Comment by hwoarangzk** [comment]
Thank you so much! It really solved the problem :)
