### ISSUE TITLE
router.use() ?

### ISSUE THREAD

**Issue by nicholaswyoung** [alexmingoia/koa-router#96]
Is there a way to register middleware for all attached handlers? For instance:

```javascript
var router = module.exports = new (require('koa-router'));

router.use(function *(next) {});

// .get, .post, etc.
```

**Comment by alexmingoia** [comment]
The next version of `koa-router` will simplify working with multiple routers and composing middleware at the router level. For now you can use `koa-compose`:

```javascript
var app = require('koa')();
var compose = require('koa-compose');
var router = new (require('koa-router'));

// puts all routes behind authMiddleware
app.use(compose([authMiddleware, router.middleware()]));
```

**Comment by alexmingoia** [comment]
... and if you want to mount routers to a path use `koa-mount`.

**Comment by nicholaswyoung** [comment]
@alexmingoia I found ```koa-compose``` and your comments at the same time. I'm glad to hear it will work with the Router instance! Thanks for your help.

**Comment by alexmingoia** [comment]
The new `4.0.0` release includes a `router.use()` for your convenience.

See https://github.com/alexmingoia/koa-router#module_koa-router--Router#use

**Comment by nicholaswyoung** [comment]
Excellent! Thanks, @alexmingoia!
