### ISSUE TITLE
Method Not Allowed.  Ordering

### ISSUE THREAD

**Issue by drewhamlett** [alexmingoia/koa-router#97]
I'm trying to do something like this

```js
let publicRouter = new Router();
publicRouter.get('/:slug', c.review.create);

let adminRouter = new Router();
adminRouter.get('/', c.admin.index);

export default {
  pub: publicRouter,
  admin: adminRouter
};

```

```js
  app.use(mount('/', pub.middleware()));
  app.use(auth({
    name: 'test',
    pass: 'test'
  }));
  app.use(mount('/admin', admin.middleware()));
```

If I mount admin above the public router everything works fine.  If I mount I below, it doesn't work.  I get the error 'method not allowed'.  Is this some kind of ordering issue?  I can't mount the public before admin because I need the auth middleware.  Thanks for your help.

**Comment by alexmingoia** [comment]
Next version of koa-router will make working with multiple routers easier by not doing 405 magic. Should be out today or tomorrow. See #92 

However, you shouldn't be using order to determine which routes use authorization middleware... use `koa-compose` instead:

```javascript
app.use(mount('/', pub.middleware()));
app.use(mount('/admin', compose([auth({
  name: 'test',
  pass: 'test'
}), admin.middleware()])));
```

**Comment by alexmingoia** [comment]
The new `4.0.0` release moves 405 and 501 responses into separate middleware. Simply use `.allowedMethods()` after you mount your other routers.

See https://github.com/alexmingoia/koa-router#routerallowedmethodsoptions--function

**Comment by drewhamlett** [comment]
Thanks for your help!
