### ISSUE TITLE
Request public router.match()

### ISSUE THREAD

**Issue by gconaty** [alexmingoia/koa-router#98]
So I've got a simple proxy that checks to see if a route exists before handing to Koa and was doing something simple like `methods = routes.v1.match(path.replace(apiRoute,'')) || [];`  This worked fine in 3.8.0 because the method was side effect free and didn't require a koa context.  Now in 4.x the arguments changed and it has side effects.  Granted it's a private API but I'm wondering if it's possible to have a public? version that preserves the old behavior.

Thanks!

**Comment by alexmingoia** [comment]
Yeah I will separate the parameter parsing and context decoration from `match()`...

**Comment by alexmingoia** [comment]
See https://github.com/alexmingoia/koa-router/blob/master/history.md#410 for what you want to do

**Comment by gconaty** [comment]
this is great.  thanks so much!
