### ISSUE TITLE
Optional params?

### ISSUE THREAD

**Issue by DylanPiercey** [alexmingoia/koa-router#99]
Is there support for optional params similar to express (Without regex).

```JavaScript
route.get('/profile/:id?', function * (next) {...});
```

**Comment by alexmingoia** [comment]
Yes, `koa-router` uses [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp#optional).

**Comment by hansfilipelo** [comment]
The answer in this issue leaves a little to be desired. While it's good to know that `koa-router` supports this, an example would also be nice since this is not listed in the README.

**Comment by cbrwizard** [comment]
And the answer is:
```js
route.get('/profile/:id*', function * (next) {...});
```

**Comment by katlimruiz** [comment]
> 
> 
> And the answer is:
> 
> ```js
> route.get('/profile/:id*', function * (next) {...});
> ```

shouldn't it be :id? (with question mark)

**Comment by GabrielNicolasAvellaneda** [comment]
> > And the answer is:
> > ```js
> > route.get('/profile/:id*', function * (next) {...});
> > ```
> 
> shouldn't it be :id? (with question mark)

It is actually :id*
[path-to-regex](https://github.com/pillarjs/path-to-regexp#optional) Says: 

> Parameters can be suffixed with an asterisk (*) to denote a zero or more parameter matches. The prefix is used for each match.

**Comment by fjeddy** [comment]
@GabrielNicolasAvellaneda 

To make a parameter optional, then it's `:id?`, to make it match the beginning of a certain string then it's `:id*`.

**URL you visit:** mydomain.com/example/123/hello

`example/:id?/hello` -> The field `id` will in this case be `123`. The ID field can be omitted, the `?` makes it optional.
`example/:id*/hello` -> The field `id` will in this case be `123/hello`. `*` matches everything after, regardless of content.

Sorry to bump an old post, just wanted to clarify a small incorrect interpretation of the documentation.
